/**
 * EvolutionSummary — Displays a narrative summary of how a brand's creative
 * identity has evolved over time, based on learning deltas and creative profiles.
 *
 * Features:
 * - Narrative generated by GPT-5.4-mini in Spanish
 * - Key shifts displayed as a timeline list with direction indicators
 * - Consolidation suggestion shown when contradictions are detected
 *
 * Requirements: Property 1 (Tenant isolation)
 */

import {
  Sparkles,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  Loader2,
  RefreshCw,
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { useEvolutionSummary, type KeyShift } from '@/hooks/useEvolutionSummary';

// ─── Props ───────────────────────────────────────────────────────────────────

interface EvolutionSummaryProps {
  /** Business ID to fetch the evolution summary for */
  businessId: string | undefined;
  /** Number of recent learning deltas to analyze (default: 30) */
  limit?: number;
}

// ─── Sub-components ──────────────────────────────────────────────────────────

function KeyShiftItem({ shift }: { shift: KeyShift }) {
  const isIncrease = shift.direction === 'increase';

  return (
    <div className="flex items-start gap-3 py-2">
      <div
        className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${
          isIncrease
            ? 'bg-green-100 dark:bg-green-950/30'
            : 'bg-red-100 dark:bg-red-950/30'
        }`}
      >
        {isIncrease ? (
          <TrendingUp className="h-3.5 w-3.5 text-green-600 dark:text-green-400" />
        ) : (
          <TrendingDown className="h-3.5 w-3.5 text-red-500 dark:text-red-400" />
        )}
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm text-foreground">{shift.description}</p>
        <p className="text-xs text-muted-foreground mt-0.5">{shift.date}</p>
      </div>
    </div>
  );
}

// ─── Main Component ──────────────────────────────────────────────────────────

export function EvolutionSummary({
  businessId,
  limit = 30,
}: EvolutionSummaryProps) {
  const {
    data,
    isLoading,
    isError,
    error,
    refetch,
    isFetching,
  } = useEvolutionSummary(businessId, limit);

  // ─── Loading state ─────────────────────────────────────────────────────────

  if (isLoading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-8">
          <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
          <span className="ml-2 text-sm text-muted-foreground">
            Analizando evolución de marca...
          </span>
        </CardContent>
      </Card>
    );
  }

  // ─── Error state ───────────────────────────────────────────────────────────

  if (isError) {
    return (
      <Card>
        <CardContent className="py-6">
          <Alert variant="destructive">
            <AlertTriangle className="h-4 w-4" />
            <AlertDescription>
              {error instanceof Error
                ? error.message
                : 'Error al cargar el resumen de evolución'}
            </AlertDescription>
          </Alert>
          <div className="mt-3 flex justify-center">
            <Button
              variant="outline"
              size="sm"
              onClick={() => refetch()}
              disabled={isFetching}
            >
              <RefreshCw className={`h-3.5 w-3.5 mr-1.5 ${isFetching ? 'animate-spin' : ''}`} />
              Reintentar
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  // ─── No data state ─────────────────────────────────────────────────────────

  if (!data) {
    return null;
  }

  const hasKeyShifts = data.key_shifts.length > 0;
  const hasConsolidation = !!data.consolidation_suggestion;

  // ─── Render ────────────────────────────────────────────────────────────────

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-violet-500" />
            <CardTitle className="text-base">Evolución de Marca</CardTitle>
          </div>
          <div className="flex items-center gap-2">
            {data.deltas_analyzed > 0 && (
              <Badge variant="secondary" className="text-xs">
                {data.deltas_analyzed} cambios analizados
              </Badge>
            )}
            <Button
              variant="ghost"
              size="sm"
              className="h-7 w-7 p-0"
              onClick={() => refetch()}
              disabled={isFetching}
              title="Actualizar resumen"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${isFetching ? 'animate-spin' : ''}`} />
            </Button>
          </div>
        </div>
      </CardHeader>

      <Separator />

      <CardContent className="pt-4 space-y-4">
        {/* Narrative */}
        <div className="rounded-lg bg-muted/50 p-3">
          <p className="text-sm leading-relaxed text-foreground">
            {data.narrative}
          </p>
          {data.profile_version > 0 && (
            <p className="text-xs text-muted-foreground mt-2">
              Perfil creativo v{data.profile_version}
            </p>
          )}
        </div>

        {/* Key Shifts */}
        {hasKeyShifts && (
          <div>
            <h4 className="text-sm font-medium text-muted-foreground mb-2">
              Cambios clave
            </h4>
            <div className="divide-y divide-border">
              {data.key_shifts.map((shift, index) => (
                <KeyShiftItem key={index} shift={shift} />
              ))}
            </div>
          </div>
        )}

        {/* Consolidation Suggestion */}
        {hasConsolidation && (
          <Alert className="border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-950/20">
            <AlertTriangle className="h-4 w-4 text-amber-600" />
            <AlertDescription className="text-sm text-amber-800 dark:text-amber-200">
              <span className="font-medium">Sugerencia de consolidación:</span>{' '}
              {data.consolidation_suggestion}
            </AlertDescription>
          </Alert>
        )}
      </CardContent>
    </Card>
  );
}
