/**
 * Hook for fetching the Evolution Summary from the evolution-summary Edge Function.
 *
 * Uses TanStack Query for caching and automatic refetching.
 * The summary is generated by GPT-5.4-mini based on learning_deltas and creative_profiles.
 *
 * Requirements: Property 1 (Tenant isolation)
 */

import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface KeyShift {
  date: string;
  description: string;
  direction: 'increase' | 'decrease';
}

export interface EvolutionSummaryData {
  narrative: string;
  key_shifts: KeyShift[];
  consolidation_suggestion: string | null;
  profile_version: number;
  deltas_analyzed: number;
}

// ─── Hook ────────────────────────────────────────────────────────────────────

/**
 * Fetches the evolution summary for a business.
 *
 * @param businessId - The business to fetch the summary for
 * @param limit - Number of recent learning deltas to analyze (default: 30)
 */
export function useEvolutionSummary(businessId: string | undefined, limit = 30) {
  return useQuery({
    queryKey: ['evolution-summary', businessId, limit],
    queryFn: async (): Promise<EvolutionSummaryData> => {
      const { data, error } = await supabase.functions.invoke(
        'evolution-summary',
        { body: { business_id: businessId, limit } },
      );

      if (error) {
        throw new Error(
          error.message ?? 'Error fetching evolution summary',
        );
      }

      if (!data?.success) {
        throw new Error(data?.error ?? 'Unknown error');
      }

      return {
        narrative: data.narrative,
        key_shifts: data.key_shifts,
        consolidation_suggestion: data.consolidation_suggestion,
        profile_version: data.profile_version,
        deltas_analyzed: data.deltas_analyzed,
      };
    },
    enabled: !!businessId,
    staleTime: 5 * 60_000, // 5 minutes — summary doesn't change frequently
    retry: 1,
  });
}
