// Types and interfaces for the Design Studio feature
// Enables creation of new templates using AI-powered generation

// --- Platform Format ---

/**
 * Platform formats supported by the Design Studio.
 * Extends the base PlatformFormat to include facebook-post as a distinct target.
 */
export type PlatformFormat =
  | 'instagram-story'   // 1080×1920
  | 'instagram-post'    // 1080×1080
  | 'facebook-post'     // 1200×628
  | 'linkedin-post'     // 1200×628
  | 'banner';           // 1920×1080

export interface PlatformDimensions {
  width: number;
  height: number;
}

/**
 * Exact pixel dimensions for each supported platform.
 * Used for mockup generation and HTML preview rendering.
 */
export const PLATFORM_DIMENSIONS: Record<PlatformFormat, PlatformDimensions> = {
  'instagram-story': { width: 1080, height: 1920 },
  'instagram-post': { width: 1080, height: 1080 },
  'facebook-post': { width: 1200, height: 628 },
  'linkedin-post': { width: 1200, height: 628 },
  'banner': { width: 1920, height: 1080 },
};

// --- Content Mode ---

/**
 * Defines how content/copy context is provided to the image generation:
 * - 'free': No content context, only visual selections. Full creative freedom.
 * - 'branch': Content ingredients loaded from a commercial branch (headlines, data, CTAs).
 * - 'custom': User provides a free-text idea/description of what they want.
 */
export type ContentMode = 'free' | 'branch' | 'custom';

// --- Image Type for Design Studio ---

/**
 * Type of image to generate. Determines the style of the visual element
 * in the mockup (photo, infographic, 3D clay, financial data).
 */
export type DesignImageType = 'foto' | 'infografia' | 'financiero';

/** Versioned master prompt selected per piece for reproducible A/B tests. */
export type MasterImagePromptVersion = 'v1' | 'v2';

/**
 * Revision of the effective image-prompt behavior. Persisted with bank items so
 * prompts built before a style/runtime change are not silently reused.
 */
export const DESIGN_STUDIO_IMAGE_PROMPT_REVISION = 'photo-natural-v3' as const;

export type CorridorMode =
  | 'auto'
  | 'geographic_corridor'
  | 'operational_route'
  | 'global_network'
  | 'bidirectional_corridor';

export type CorridorFlowType = 'auto' | 'payment' | 'goods' | 'bidirectional';

/** Optional user override; `auto` lets the image prompt infer from copy/context. */
export interface CorridorOverride {
  mode: CorridorMode;
  flowType: CorridorFlowType;
  originCountry: string;
  destinationCountry: string;
}

export interface CorridorAnalysis {
  mode: Exclude<CorridorMode, 'auto'>;
  flow_type: Exclude<CorridorFlowType, 'auto'> | 'network' | 'shipment_status';
  origin_country: string | null;
  destination_country: string | null;
  direction: string | null;
  confidence: 'high' | 'medium' | 'low';
  evidence: string;
}

// --- Piece Copy (specific copy for the mockup) ---

/**
 * Specific copy to include in the mockup. When provided, GPT Image 2
 * uses this exact text instead of inventing copy.
 */
export interface PieceCopy {
  headline: string;
  body?: string;
  cta?: string;
  punchline?: string;
}

// --- Image Prompt (specific image direction) ---

/**
 * Specific image prompt for the visual element in the mockup.
 * Generated by generate-design-image or written manually.
 */
export interface PieceImagePrompt {
  type: DesignImageType;
  prompt: string;
}

// --- Copy Bank (Design Studio 2-stage flow) ---

/**
 * How the image for a bank copy is produced:
 * - 'single': one image.
 * - 'carousel': the seed copy is exploded into N chained slides, each with its
 *   own slide copy, its own self-contained prompt and its own image. Slides are
 *   rendered one at a time so a bad slide is regenerated alone.
 */
export type CopyBankImageMode = 'single' | 'carousel';

// --- Carousel (Design Studio Stage C) ---

/**
 * Narrative function of a slide. Values stay in English because they are
 * persisted in `piece_v2`; the UI labels them in Spanish.
 *
 * Two families live here on purpose:
 * - `tension | shift | risk | solution | cta` — the five beats the approved copy
 *   bank actually uses (`docs/prompts/copy-banks/_contexto-maestro.*`, §26).
 * - `hook | problem | example` — the original four-slide shape. Kept because
 *   carousels already saved in `piece_v2` carry these roles and have to keep
 *   rendering after a reload.
 */
export type CarouselSlideRole =
  | 'tension'
  | 'shift'
  | 'risk'
  | 'solution'
  | 'cta'
  | 'hook'
  | 'problem'
  | 'example';

/** Render lifecycle for a slide (drives the per-slot queue UI). */
export type CarouselSlotStatus =
  | 'idle'
  | 'queued'
  | 'generating'
  | 'done'
  | 'error';

/** Brand elements composited on a slide AFTER its image is generated. */
export type CarouselBrandElement = 'logo' | 'disclaimer';

/**
 * Copy rendered on a single slide.
 *
 * `headline` is the only guaranteed field: it holds the line the slide is about.
 * On a `singleLine` preset it is the WHOLE slide — including the closing slide,
 * whose headline is the call to action itself. `cta` therefore only carries text
 * on presets that end with a solution slide instead of a dedicated CTA slide.
 */
export interface CarouselSlideCopy {
  headline: string;
  body?: string;
  cta?: string;
}

/**
 * Canvas for every carousel slide: the same square the existing `instagram-post`
 * flow already renders, so the carousel inherits a size that is known to work
 * end to end instead of introducing a new one.
 *
 * One square set covers both platforms: Instagram takes the slides as separate
 * images, LinkedIn packs the same ones into a multi-page PDF (its swipeable
 * "carousel" is a document post, and 1:1 is a supported document size).
 *
 * Single source of truth on purpose — changing the format means changing these
 * two values and nothing else.
 */
export const CAROUSEL_DIMENSIONS: PlatformDimensions = { width: 1024, height: 1024 };

/** Aspect ratio sent to the image model, kept in sync with the dimensions. */
export const CAROUSEL_ASPECT_RATIO = '1:1' as const;

/**
 * One slide of a carousel: its copy, its prompt and where its image landed.
 */
export interface CarouselSlot {
  id: string;
  /** 0-based position. Also the reading order and the export order. */
  index: number;
  role: CarouselSlideRole;
  /**
   * Copy for this slide. Must be final BEFORE the prompt is built: the exact
   * spelling is baked into the prompt, so editing it later means regenerating.
   */
  slideCopy: CarouselSlideCopy;
  /**
   * What this slide's image must communicate, from the script agent. Persisted
   * because rebuilding the prompts after a reload needs it.
   */
  imageIntent: string;
  /**
   * Self-contained image prompt. Carries the full design block verbatim (not a
   * delta over a shared base), so this slide can be edited and regenerated on
   * its own without losing the visual system.
   */
  prompt: string;
  /**
   * Brand elements this slide reserves negative space for. Slides with no brand
   * element use the whole frame.
   */
  brandElements: CarouselBrandElement[];
  status: CarouselSlotStatus;
  /** Rendered result. Base64 is deliberately NOT stored: it would add megabytes
   *  to the `piece_v2` JSONB and be refetched on every copy-bank query. */
  mockupId?: string;
  imageUrl?: string;
  error?: string;
}

/**
 * A carousel hanging off its seed copy in the bank. One carousel per bank row.
 */
export interface CarouselMeta {
  presetSlug: string;
  /**
   * The design block shared verbatim by every slide prompt. Persisted so a
   * single slide can be rebuilt from scratch and still match the set.
   */
  visualAnchor: string;
  /** Ties the rendered images together (`design_mockups.carousel_group_id`). */
  groupId: string;
  /** Medium picked for the whole set — mixing mediums breaks the set. */
  imageType: DesignImageType;
  slots: CarouselSlot[];
  createdAt: string;
}

/**
 * A narrative shape for a carousel. The preset — not the agent — decides how
 * many slides there are and which ones carry brand elements, so adding
 * "mito vs realidad" or "3 pasos" later needs no change to the agent.
 */
export interface CarouselPreset {
  slug: string;
  name: string;
  description: string;
  /** One entry per slide, in reading order. Length = number of slides. */
  roles: CarouselSlideRole[];
  /**
   * Which slide carries each brand element, addressed by role so the mapping
   * survives presets of different lengths. Omit an element to leave it off.
   *
   * The disclaimer rides the slide that makes the claim, not automatically the
   * last one: a legal note has to sit next to the number it qualifies.
   */
  brandPlacement: Partial<Record<CarouselBrandElement, CarouselSlideRole>>;
  /**
   * Every slide carries ONE line and nothing else — no headline/body split.
   *
   * This is how the approved bank writes carousels: the slides read as a single
   * sentence cut into pieces, so a second text level on the same slide is not
   * hierarchy, it is the same idea said twice. It also buys the opening slide the
   * room to keep a two-clause contrast intact instead of splitting it across two
   * type sizes, which is what broke the first version of this flow.
   */
  singleLine?: boolean;
}

export const CAROUSEL_ROLE_LABELS: Record<CarouselSlideRole, string> = {
  tension: 'Tensión',
  shift: 'Qué cambia',
  risk: 'Qué riesgo',
  solution: 'Solución',
  cta: 'CTA',
  hook: 'Gancho',
  problem: 'Problema',
  example: 'Ejemplo',
};

/**
 * Short brief given to the script agent for each role.
 *
 * These are transcribed from what the 10 approved carousels actually do, not from
 * a generic content-marketing arc. Two of them used to fight the copy bank and
 * are worded defensively now: the opening slide kept getting split in half, and
 * the third slide kept inventing a bare figure because its brief asked for
 * "numbers".
 */
export const CAROUSEL_ROLE_BRIEFS: Record<CarouselSlideRole, string> = {
  tension:
    'La tensión, completa, en una sola línea. Es el headline semilla íntegro: si son dos oraciones en contraste, van las dos. Prohibido partirlo en dos niveles de texto.',
  shift:
    'Qué puede cambiar entre hoy y el momento del pago. Una frase, en condicional.',
  risk:
    'Qué riesgo genera ese cambio para la empresa. Continúa la frase anterior ("ese movimiento…", "y con él…"). Sin cifras inventadas.',
  solution:
    'Cómo ayuda la solución. El sujeto es el producto, no el cliente: "puede ayudar a…". Sin imperativos y sin claims que no estén autorizados.',
  cta: 'Solo el CTA, escrito en el campo headline. Nada más en el slide.',
  hook: 'Detiene el scroll. Es el headline del copy semilla completo, casi tal cual.',
  problem: 'El costo concreto de no resolverlo. Nada abstracto.',
  example:
    'El riesgo concreto que eso genera. Un monto suelto no es un ejemplo: si usas una cifra, va la operación completa y etiquetada como ilustrativa.',
};

export const CAROUSEL_PRESETS: CarouselPreset[] = [
  {
    slug: 'tension-shift-risk-solution-cta',
    name: 'Tensión → Qué cambia → Riesgo → Solución → CTA',
    description:
      'Los cinco tiempos del banco de copys aprobado: una sola línea por slide y el CTA solo al cierre.',
    roles: ['tension', 'shift', 'risk', 'solution', 'cta'],
    // Logo on the cover: it is the only slide everyone sees in the feed.
    // Disclaimer on the solution, the one slide that makes a product claim —
    // this shape carries no figures, so there is nothing to qualify earlier.
    brandPlacement: { logo: 'tension', disclaimer: 'solution' },
    singleLine: true,
  },
  {
    slug: 'hook-problem-example-solution',
    name: 'Gancho → Problema → Ejemplo → Solución',
    description:
      'Arco de 4 slides con headline y body por slide. Cierra con el CTA en el último.',
    roles: ['hook', 'problem', 'example', 'solution'],
    brandPlacement: { logo: 'hook', disclaimer: 'example' },
  },
];

export const DEFAULT_CAROUSEL_PRESET_SLUG = 'tension-shift-risk-solution-cta';

export function getCarouselPreset(slug: string): CarouselPreset {
  return (
    CAROUSEL_PRESETS.find((p) => p.slug === slug) ?? CAROUSEL_PRESETS[0]
  );
}

/** Brand elements a given role carries under a preset. */
export function brandElementsForRole(
  preset: CarouselPreset,
  role: CarouselSlideRole,
): CarouselBrandElement[] {
  return (Object.entries(preset.brandPlacement) as Array<
    [CarouselBrandElement, CarouselSlideRole]
  >)
    .filter(([, target]) => target === role)
    .map(([element]) => element);
}

/**
 * Design-Studio-specific payload stored inside `generated_ideas.piece_v2`
 * (JSONB). Using the existing column avoids a schema migration while marking
 * the row's origin (`source`) so the pipeline's IdeasPanel can filter it out.
 * The multichannel render only reads piece_v2 when it has `overlays`+`captions`,
 * so this shape is never misinterpreted there.
 */
export interface DesignStudioIdeaMeta {
  source: 'design_studio';
  angleName?: string | null;
  industryName?: string | null;
  imageMode: CopyBankImageMode;
  imageType?: DesignImageType;   // active type for single mode
  imagePrompt?: string;          // generated prompt for single mode
  imagePromptRevision?: string;  // invalidates cached prompts after runtime/style changes
  masterImagePromptVersion?: MasterImagePromptVersion; // exact V1/V2 snapshot used
  imageBackgroundStyle?: 'navy' | 'light_cream' | 'white' | 'white_2';
  corridorOverride?: CorridorOverride;
  corridorAnalysis?: CorridorAnalysis;
  /** Carousel derived from this copy (Stage C). One per bank row. */
  carousel?: CarouselMeta;
  // Feedback loop: 'liked' copies steer new batches (imitate tone), 'disliked'
  // ones are avoided. A user-corrected+saved copy is auto-marked 'liked'.
  rating?: 'liked' | 'disliked';
}

/** Marker string kept in one place so producers and filters never drift. */
export const DESIGN_STUDIO_SOURCE = 'design_studio' as const;

/** True when a generated_ideas row originated in the Design Studio copy bank. */
export function isDesignStudioIdea(pieceV2: unknown): boolean {
  return !!pieceV2 && typeof pieceV2 === 'object'
    && (pieceV2 as { source?: string }).source === DESIGN_STUDIO_SOURCE;
}

// --- Visual Selections (Mode A) ---

export interface VisualSelections {
  background: string | null;    // white-classic | white-xending-v2 | white-2 | dark-navy | legacy/custom
  visualStyle: string | null;   // 'minimalist' | 'glassmorphism' | 'bold' | 'financial' | 'gradients' | 'hero-photo' | custom
  contentType: string | null;   // 'stat' | 'news' | 'educational' | 'promo' | 'comparison' | 'event' | 'testimonial' | custom
  heroElement: string | null;   // 'big-number' | 'main-photo' | 'icon' | 'floating-badge' | 'no-image' | custom
  platform: PlatformFormat | null;
  // Content context
  contentMode: ContentMode;
  commercialBranchSlug: string | null;  // only when contentMode === 'branch'
  customIdea: string | null;            // only when contentMode === 'custom'
  // Narrative angle (only when contentMode === 'branch'). Drives copy variety
  // and enables persistence to content_library for cross-session de-duplication.
  // Mirrors the dimensions used by the Generador Combinable flow.
  narrativeAngleId: string | null;
  narrativeAngleSlug: string | null;
  narrativeAngleName: string | null;
  funnelStage: string | null;
  narrativePromptInstruction: string | null;
  // Industry/vertical dimension. Adds per-industry relevance + variety.
  // industryAuto = cycle through all verticals per generation (max variety).
  industryVerticalId: string | null;
  industryVerticalName: string | null;
  industryAuto: boolean;
  // Piece-level copy and image prompt (optional, for full-package mode)
  pieceCopy: PieceCopy | null;
  pieceImagePrompt: PieceImagePrompt | null;
  // Optional route hints for mapa_rutas. Auto mode infers from copy/context.
  corridorOverride?: CorridorOverride;
  // When true, the AI bakes the exact headline/CTA into the generated image.
  // When false (default), the image stays text-free and the template overlays copy.
  textInImage: boolean;
}

/** Full narrative angle payload returned by AngleSelector. */
export interface NarrativeAngleSelection {
  id: string;
  slug: string;
  name: string;
  funnelStage: string;
  promptInstruction: string;
}

/** Industry selection: a specific vertical, 'auto' (cycle) or null (none). */
export type IndustrySelection = { id: string; name: string } | 'auto' | null;

export type SelectionCategory = 'background' | 'visualStyle' | 'contentType' | 'heroElement' | 'platform';

export interface SelectionOption {
  value: string;
  label: string;
  icon?: string;        // Lucide icon name
  description?: string;
}

export interface CategoryConfig {
  id: SelectionCategory;
  label: string;
  options: SelectionOption[];
  allowCustom: boolean;
}

// --- Brand Palette ---

export interface BrandPalette {
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  fonts: {
    display?: string;
    body?: string;
    mono?: string;
  };
  logo_url: string;
  disclaimer?: string;
}

// --- Generated Mockups ---

export interface GeneratedMockup {
  index: number;
  image_base64: string;
  prompt_used: string;
}

// --- HTML Iteration ---

export interface HtmlIteration {
  version: number;
  html: string;
  feedback: string | null;  // null for the first version
  created_at: string;
}

// --- Design Session ---

export type DesignSessionStatus = 'active' | 'completed' | 'discarded';

export interface DesignSession {
  id: string;
  business_id: string;
  status: DesignSessionStatus;
  input_mode: 'visual' | 'reference';
  selections: VisualSelections | null;
  reference_image_url: string | null;
  reference_description: string | null;
  platform: PlatformFormat | null;
  mockups: GeneratedMockup[];
  selected_mockup_index: number | null;
  current_html: string | null;
  html_history: HtmlIteration[];
  iteration_count: number;
  created_at: string;
  updated_at: string;
}

// --- Template Converter ---

export interface TemplateSlot {
  name: string;           // 'headline' | 'subcopy' | 'cta' | 'imageUrl' | 'disclaimer'
  type: 'text' | 'image';
  required: boolean;
}

export interface TemplateConverterInput {
  html: string;
  brand_palette: BrandPalette;
}

export interface TemplateConverterOutput {
  template_html: string;          // HTML with {{placeholders}}
  detected_slots: TemplateSlot[]; // Detected slots
}

// --- API Request/Response Types ---

// --- Branch Content Ingredients ---

/**
 * Pre-approved content ingredients for a commercial branch + angle combination.
 * These are injected into the image generation prompt as available content
 * that GPT can use creatively (not prescriptive layout).
 */
export interface BranchContentIngredients {
  headlines: string[];
  sublines: string[];
  ctas: string[];
  benefit_phrases?: string[];
  data_sets?: Record<string, string>[];
  big_stats?: string[];
  photo_direction: string;
  // Strategic context that differentiates this branch from others
  branch_context?: {
    name: string;
    objetivo?: string;
    dolor?: string;
    promesa?: string;
  };
}

export interface GenerateMockupsRequest {
  business_id: string;
  brand_palette: BrandPalette;
  mode: 'visual' | 'reference';
  // Mode A
  selections?: VisualSelections;
  // Mode B
  reference_image_base64?: string;
  reference_description?: string;
  // Content context (new)
  content_mode?: ContentMode;
  branch_ingredients?: BranchContentIngredients;
  custom_idea?: string;
  // Piece-level copy and image prompt
  piece_copy?: PieceCopy;
  piece_image_prompt?: PieceImagePrompt;
  // Iteration feedback — regenerate with user corrections
  iteration_feedback?: string;
  previous_prompt?: string;
  // Common
  platform: PlatformFormat;
  count: 3;
}

export interface GenerateMockupsResponse {
  mockups: GeneratedMockup[];
}

export interface DesignHtmlFromMockupRequest {
  business_id: string;
  brand_palette: BrandPalette;
  mockup_image_base64: string;
  platform: PlatformFormat;
  // For iterations
  current_html?: string;
  iteration_feedback?: string;
}

export interface DesignHtmlResponse {
  html: string;
}

export interface SaveTemplateRequest {
  name: string;
  business_id: string;
  template_html: string;
  platform: PlatformFormat;
  slots: TemplateSlot[];
  source_mockup_url?: string;
  thumbnail_base64?: string;
}

export interface SaveTemplateResponse {
  id: string;
  name: string;
  created_at: string;
}

// --- Zustand Store Types ---

export interface DesignStudioState {
  // Session
  sessionId: string | null;
  sessionStatus: DesignSessionStatus;

  // Brand Palette (loaded automatically)
  brandPalette: BrandPalette | null;

  // Input mode
  inputMode: 'visual' | 'reference';

  // Mode A: Visual selections
  selections: VisualSelections;

  // Mode B: Reference image
  referenceImage: File | null;
  referenceImagePreview: string | null;
  referenceDescription: string;

  // Platform
  selectedPlatform: PlatformFormat | null;

  // Generated mockups
  mockups: GeneratedMockup[];
  selectedMockupIndex: number | null;

  // Copy bank: which candidate (generated_ideas row id) is currently active.
  // The active candidate's copy is mirrored into selections.pieceCopy so the
  // Stage-B visual editor and mockup generation consume it unchanged.
  activeCandidateId: string | null;

  // HTML
  currentHtml: string | null;
  htmlHistory: HtmlIteration[];
  iterationCount: number;

  // Loading states
  isGeneratingMockups: boolean;
  isGeneratingHtml: boolean;
  isSaving: boolean;
  error: string | null;
}

export interface DesignStudioActions {
  // Session
  initSession(): void;
  restoreSession(session: DesignSession): void;
  discardSession(): void;
  markSessionCompleted(): void;

  // Selections
  setInputMode(mode: 'visual' | 'reference'): void;
  setSelection(category: SelectionCategory, value: string): void;
  setCustomValue(category: SelectionCategory, value: string): void;
  setPlatform(platform: PlatformFormat): void;

  // Content mode
  setContentMode(mode: ContentMode): void;
  setCommercialBranch(slug: string | null): void;
  setCustomIdea(idea: string): void;
  setNarrativeAngle(angle: NarrativeAngleSelection | null): void;
  setIndustryVertical(industry: IndustrySelection): void;

  // Piece copy & image prompt
  setPieceCopy(copy: PieceCopy | null): void;
  updatePieceCopyField(field: keyof PieceCopy, value: string): void;
  setPieceImagePrompt(prompt: PieceImagePrompt | null): void;
  setPieceImageType(type: DesignImageType): void;
  setPieceImagePromptText(text: string): void;
  setCorridorOverride(corridor: CorridorOverride): void;
  setTextInImage(value: boolean): void;

  // Reference
  setReferenceImage(file: File | null): void;
  setReferenceDescription(desc: string): void;

  // Mockups
  setMockups(mockups: GeneratedMockup[]): void;
  selectMockup(index: number): void;
  invalidateGeneratedVisuals(): void;

  // Copy bank
  setActiveCandidate(id: string | null, copy: PieceCopy | null): void;

  // HTML
  setCurrentHtml(html: string): void;
  addIteration(html: string, feedback: string): void;

  // Loading
  setGeneratingMockups(loading: boolean): void;
  setGeneratingHtml(loading: boolean): void;
  setSaving(loading: boolean): void;
  setError(error: string | null): void;

  // Reset
  reset(): void;
}

export type DesignStudioStore = DesignStudioState & DesignStudioActions;
