// Types and interfaces for the Design Studio feature
// Enables creation of new templates using AI-powered generation

/**
 * Las cuatro banderas que describen cómo se lee un preset.
 *
 * Se importan de `_shared` y no se redeclaran aquí porque el validador del plan las lee
 * del otro lado: dos definiciones de "beats independientes" acabarían discrepando, que
 * es exactamente lo que pasó entre el copy kit y `prompt_kit`. El módulo no importa nada
 * por URL, así que el bundler lo resuelve igual que Deno.
 */
import {
  CAROUSEL_FORWARD_MARGIN_FACT_KEYS,
  CAROUSEL_MAX_FX_RATE,
  CAROUSEL_MAX_OPERATION_USD,
  CAROUSEL_MIN_FX_RATE,
  CAROUSEL_MIN_OPERATION_USD,
  CAROUSEL_SCENARIO_FACT_KEYS,
} from '../../supabase/functions/_shared/carousel-plan-types';
import type {
  CarouselCommercialIntent,
  CarouselCreativePlan,
  CarouselEconomicFact,
  CarouselEconomicFactKey,
  CarouselEconomicScenario,
  CarouselFigureScenarioId,
  CarouselFigureSurface,
  CarouselFigureWeight,
  CarouselPlanDigest,
  PresetBeatCoupling,
  PresetClosingPolicy,
  PresetLayoutPolicy,
  PresetSeedUsage,
} from '../../supabase/functions/_shared/carousel-plan-types';

export {
  CAROUSEL_MAX_FX_RATE,
  CAROUSEL_MAX_OPERATION_USD,
  CAROUSEL_MIN_FX_RATE,
  CAROUSEL_MIN_OPERATION_USD,
};

export type {
  CarouselCommercialIntent,
  CarouselCreativePlan,
  CarouselEconomicFact,
  CarouselEconomicFactKey,
  CarouselEconomicScenario,
  CarouselFigureScenarioId,
  CarouselFigureSurface,
  CarouselFigureWeight,
  CarouselPlanDigest,
  PresetBeatCoupling,
  PresetClosingPolicy,
  PresetLayoutPolicy,
  PresetSeedUsage,
};

// --- Platform Format ---

/**
 * Platform formats supported by the Design Studio.
 * Extends the base PlatformFormat to include facebook-post as a distinct target.
 */
export type PlatformFormat =
  | 'instagram-story'   // 1080×1920
  | 'instagram-post'    // 1080×1080
  | 'facebook-post'     // 1200×628
  | 'linkedin-post'     // 1200×628
  | 'banner';           // 1920×1080

export interface PlatformDimensions {
  width: number;
  height: number;
}

/**
 * Exact pixel dimensions for each supported platform.
 * Used for mockup generation and HTML preview rendering.
 */
export const PLATFORM_DIMENSIONS: Record<PlatformFormat, PlatformDimensions> = {
  'instagram-story': { width: 1080, height: 1920 },
  'instagram-post': { width: 1080, height: 1080 },
  'facebook-post': { width: 1200, height: 628 },
  'linkedin-post': { width: 1200, height: 628 },
  'banner': { width: 1920, height: 1080 },
};

// --- Content Mode ---

/**
 * Defines how content/copy context is provided to the image generation:
 * - 'free': No content context, only visual selections. Full creative freedom.
 * - 'branch': Content ingredients loaded from a commercial branch (headlines, data, CTAs).
 * - 'custom': User provides a free-text idea/description of what they want.
 */
export type ContentMode = 'free' | 'branch' | 'custom';

// --- Image Type for Design Studio ---

/**
 * Type of image to generate. Determines the style of the visual element
 * in the mockup (photo, infographic, 3D clay, financial data).
 */
export type DesignImageType = 'foto' | 'infografia' | 'financiero';

/** Versioned master prompt selected per piece for reproducible A/B tests. */
export type MasterImagePromptVersion = 'v1' | 'v2';

/**
 * Revision of the effective image-prompt behavior. Persisted with bank items so
 * prompts built before a style/runtime change are not silently reused.
 */
export const DESIGN_STUDIO_IMAGE_PROMPT_REVISION = 'photo-natural-v3' as const;

export type CorridorMode =
  | 'auto'
  | 'geographic_corridor'
  | 'operational_route'
  | 'global_network'
  | 'bidirectional_corridor';

export type CorridorFlowType = 'auto' | 'payment' | 'goods' | 'bidirectional';

/** Optional user override; `auto` lets the image prompt infer from copy/context. */
export interface CorridorOverride {
  mode: CorridorMode;
  flowType: CorridorFlowType;
  originCountry: string;
  destinationCountry: string;
}

export interface CorridorAnalysis {
  mode: Exclude<CorridorMode, 'auto'>;
  flow_type: Exclude<CorridorFlowType, 'auto'> | 'network' | 'shipment_status';
  origin_country: string | null;
  destination_country: string | null;
  direction: string | null;
  confidence: 'high' | 'medium' | 'low';
  evidence: string;
}

// --- Piece Copy (specific copy for the mockup) ---

/**
 * Specific copy to include in the mockup. When provided, GPT Image 2
 * uses this exact text instead of inventing copy.
 */
export interface PieceCopy {
  headline: string;
  body?: string;
  cta?: string;
  punchline?: string;
}

// --- Image Prompt (specific image direction) ---

/**
 * Specific image prompt for the visual element in the mockup.
 * Generated by generate-design-image or written manually.
 */
export interface PieceImagePrompt {
  type: DesignImageType;
  prompt: string;
}

// --- Copy Bank (Design Studio 2-stage flow) ---

/**
 * How the image for a bank copy is produced:
 * - 'single': one image.
 * - 'carousel': the seed copy is exploded into N chained slides, each with its
 *   own slide copy, its own self-contained prompt and its own image. Slides are
 *   rendered one at a time so a bad slide is regenerated alone.
 */
export type CopyBankImageMode = 'single' | 'carousel';

// --- Carousel (Design Studio Stage C) ---

/**
 * Narrative function of a slide. Values stay in English because they are
 * persisted in `piece_v2`; the UI labels them in Spanish.
 *
 * Several families live here on purpose:
 * - `tension | shift | risk | solution | cta` — the five beats the approved copy
 *   bank actually uses (`docs/prompts/copy-banks/_contexto-maestro.*`, §26).
 * - `hook | problem | example` — the original four-slide shape. Kept because
 *   carousels already saved in `piece_v2` carry these roles and have to keep
 *   rendering after a reload.
 * - `promise | signal | close` — the checklist, whose slides are INDEPENDENT of
 *   each other and can be read in any order.
 * - `moment | outcome` — the timeline, whose slides are dates rather than
 *   arguments.
 *
 * A role may repeat inside a preset (a checklist is three `signal` slides), which
 * is why anything that addresses a single slide has to go through its index. See
 * `brandElementsForSlide`.
 */
export type CarouselSlideRole =
  | 'tension'
  | 'shift'
  | 'risk'
  | 'solution'
  | 'cta'
  | 'hook'
  | 'problem'
  | 'example'
  | 'promise'
  | 'signal'
  | 'moment'
  | 'outcome'
  | 'close';

/** Render lifecycle for a slide (drives the per-slot queue UI). */
export type CarouselSlotStatus =
  | 'idle'
  | 'queued'
  | 'generating'
  | 'done'
  | 'error';

/** Brand elements composited on a slide AFTER its image is generated. */
export type CarouselBrandElement = 'logo' | 'disclaimer';

/**
 * How much text the piece is designed around.
 *
 * This is an art-direction decision, not a technical limit. Image models render
 * short strings reliably enough now that a slide can be built as a finished
 * editorial ad — dominant headline, small supporting line, meaningful labels
 * inside the objects — instead of a photograph with a caption on top.
 *
 * `MINIMAL_TEXT` is declared but not implemented: it exists so the mode is a
 * dimension of the preset from the start rather than a retrofit later.
 */
export type CarouselVisualMode = 'EDITORIAL_FULL_TEXT' | 'MINIMAL_TEXT';

/**
 * Composition architecture of a slide.
 *
 * The layout is chosen per slide by what the message needs, and the set must not
 * repeat one: five slides under the same template read as filled-in placeholders
 * even when each scene differs.
 */
export type CarouselLayout =
  /** Headline across the top, supporting line under it, conceptual scene below. */
  | 'editorial_top'
  /** Headline and copy in the left column, photography holding the right. */
  | 'split_photo'
  /** Repetition into depth: the same object and document, several times. */
  | 'editorial_repetition'
  /** A document or result, organised and resolved, as the subject. */
  | 'document_result'
  /** Clean hero shot, minimum complexity. Closing frame. */
  | 'hero_clean';

export const CAROUSEL_LAYOUT_LABELS: Record<CarouselLayout, string> = {
  editorial_top: 'Editorial superior',
  split_photo: 'Split con fotografía',
  editorial_repetition: 'Repetición',
  document_result: 'Documento / resultado',
  hero_clean: 'Hero limpio',
};

/**
 * What the carousel is FOR, which is a different axis from how it reads.
 *
 * The preset decides the structure; this decides who owns the closing sentence and
 * whether the brand is named at all. They were fused before, and the result was
 * that every set ended on "Xending puede ayudar a…" regardless of what it was for:
 * the closing rule lived in the prompt as a single fixed instruction.
 *
 * Naming the brand is not what makes a piece branded — the logo is composited on
 * the cover of every set. A piece that explains something and never says the name
 * is still recognisably ours, and it is the version people actually forward.
 */
export type CarouselObjective = 'explicar' | 'conectar' | 'vender';

export const CAROUSEL_OBJECTIVES: {
  value: CarouselObjective;
  label: string;
  /** What it changes about the copy, in the panel's own words. */
  hint: string;
}[] = [
  {
    value: 'explicar',
    label: 'Explicar',
    hint: 'Cierra en la idea. El texto no nombra la marca ni le ordena nada al lector: la marca la pone el logo.',
  },
  {
    value: 'conectar',
    label: 'Conectar',
    hint: 'Cierra en la categoría de solución ("una cobertura puede…"), con una invitación suave. Máximo una mención de marca.',
  },
  {
    value: 'vender',
    label: 'Vender',
    hint: 'Cierra con la marca como sujeto y el CTA imperativo del banco. Es el único objetivo donde el nombre va en el texto.',
  },
];

export const DEFAULT_CAROUSEL_OBJECTIVE: CarouselObjective = 'conectar';

/**
 * What a highlighted block MEANS. The colour is derived from this, not chosen.
 *
 * Keeping the role and the colour apart is what makes the code readable as a
 * system: the agent decides that a phrase carries risk, and the brand decides that
 * risk is coral. Changing the palette then touches one mapping instead of every
 * prompt that ever named a hex.
 */
export type CarouselColorRole = 'risk' | 'control';

/** Brand meaning of each colour. Mirrors `_shared/brandColorLanguage.ts`. */
export const CAROUSEL_ROLE_COLOR: Record<CarouselColorRole, string> = {
  /** Future and its exposure: PAGO, increase, variation, impact. */
  risk: '#FF7A4A',
  /** Present and what is under control: HOY, current value, Xending. */
  control: '#2ED4C7',
};

/**
 * A block of the headline that carries typographic emphasis.
 *
 * `text` is a complete semantic unit, not a lone word: "tus costos" highlighted
 * whole reads better than "costos" on its own. It must appear verbatim inside the
 * headline — emphasis on text that is not there cannot be rendered.
 *
 * One block normally. Two only when the line holds a real opposition (USD against
 * MXN), because then the colour is information rather than decoration.
 */
export interface CarouselHighlight {
  text: string;
  colorRole: CarouselColorRole;
}

/**
 * Copy rendered on a single slide.
 *
 * Under `EDITORIAL_FULL_TEXT` all three levels have a job: `headline` is the
 * dominant element, `body` is the sentence that lands it, and `cta` closes. The
 * hierarchy between them is the point — a supporting line that competes with the
 * headline breaks the piece.
 *
 * `headline` may carry newlines. They are editorial line breaks chosen by meaning
 * ("Tu factura / está en dólares. / Tu presupuesto, / en pesos") and have to
 * survive to the image prompt, so nothing in this flow may collapse them.
 */
export interface CarouselSlideCopy {
  headline: string;
  body?: string;
  cta?: string;
}

/**
 * The art direction of one slide, decided before any image prompt exists.
 *
 * This is what turns "text plus a related photo" into a designed piece: what the
 * image has to prove, the metaphor that proves it, the composition that carries
 * it, and the words allowed to appear inside the objects. Persisted so a
 * regeneration keeps the same intent instead of drifting back to a hero shot.
 */
export interface CarouselSlideBrief {
  /** What the image must make evident, in one sentence. */
  visualIntent: string;
  /** The concrete device that demonstrates it. */
  visualMetaphor: string;
  layout: CarouselLayout;
  /** The objects that must be in frame. */
  primaryObjects: string[];
  /**
   * Short labels allowed to render inside documents, screens and tags — "USD",
   * "MXN", "HOY", "60 DÍAS", "TOTAL". They come from here so the model is not
   * inventing financial data, and they are what lets an object explain a concept
   * instead of another sentence doing it.
   */
  environmentalText: string[];
  /** Typographic emphasis, by semantic unit. One block, or two when opposed. */
  highlights: CarouselHighlight[];
  /**
   * Hechos calculados que este beat debe volver visibles. No prescriben una tabla:
   * pueden vivir en una etiqueta sobre producto, una banda de margen o un espacio.
   */
  economicFacts?: CarouselEconomicFact[];
  /** Cómo se integra la cifra al cuadro; separado de los valores para permitir variedad. */
  figurePresentation?: {
    scenarioId: Exclude<CarouselFigureScenarioId, 'none'>;
    qualifier: 'ESCENARIO ILUSTRATIVO';
    narrativePurpose: string;
    weight: CarouselFigureWeight;
    suggestedSurface: CarouselFigureSurface;
  };
  /**
   * Adaptador documental legacy. Se conserva para carruseles persistidos y para beats
   * cuya superficie elegida sea realmente `document`.
   */
  documents?: CarouselFigureDocument[];
  /** La suma de las diferencias. Legacy para el adaptador documental. */
  accumulatedLabel?: string;
}

/**
 * Canvas for every carousel slide: the same square the existing `instagram-post`
 * flow already renders, so the carousel inherits a size that is known to work
 * end to end instead of introducing a new one.
 *
 * One square set covers both platforms: Instagram takes the slides as separate
 * images, LinkedIn packs the same ones into a multi-page PDF (its swipeable
 * "carousel" is a document post, and 1:1 is a supported document size).
 *
 * Single source of truth on purpose — changing the format means changing these
 * two values and nothing else.
 */
export const CAROUSEL_DIMENSIONS: PlatformDimensions = { width: 1024, height: 1024 };

/** Aspect ratio sent to the image model, kept in sync with the dimensions. */
export const CAROUSEL_ASPECT_RATIO = '1:1' as const;

/**
 * One slide of a carousel: its copy, its prompt and where its image landed.
 */
export interface CarouselSlot {
  id: string;
  /** 0-based position. Also the reading order and the export order. */
  index: number;
  role: CarouselSlideRole;
  /**
   * Copy for this slide. Must be final BEFORE the prompt is built: the exact
   * spelling is baked into the prompt, so editing it later means regenerating.
   */
  slideCopy: CarouselSlideCopy;
  /**
   * What this slide's image must communicate, from the script agent. Persisted
   * because rebuilding the prompts after a reload needs it.
   */
  imageIntent: string;
  /**
   * Art direction for this slide. Optional because carousels saved before this
   * existed have none, and those still have to load.
   */
  brief?: CarouselSlideBrief;
  /**
   * Self-contained image prompt. Carries the full design block verbatim (not a
   * delta over a shared base), so this slide can be edited and regenerated on
   * its own without losing the visual system.
   */
  prompt: string;
  /**
   * Brand elements this slide reserves negative space for. Slides with no brand
   * element use the whole frame.
   */
  brandElements: CarouselBrandElement[];
  status: CarouselSlotStatus;
  /** Rendered result. Base64 is deliberately NOT stored: it would add megabytes
   *  to the `piece_v2` JSONB and be refetched on every copy-bank query. */
  mockupId?: string;
  imageUrl?: string;
  error?: string;
}

/**
 * A carousel hanging off its seed copy in the bank. One carousel per bank row.
 */
export interface CarouselMeta {
  presetSlug: string;
  /**
   * What the set is for. Absent on carousels created before this existed, which
   * read as 'vender' because that is what the old fixed rules produced.
   */
  objective?: CarouselObjective;
  /** Mecanismo comercial explícito; ausente en carruseles legacy. */
  commercialIntent?: CarouselCommercialIntent;
  /**
   * The design block shared verbatim by every slide prompt. Persisted so a
   * single slide can be rebuilt from scratch and still match the set.
   */
  visualAnchor: string;
  /**
   * Recurring subject that threads the slides together.
   *
   * Persisted because the user can edit it and because `buildPrompts` sends it on
   * every call: without it here, reloading the page dropped the motif and the
   * rebuilt set lost the thread that made it read as a series.
   */
  visualMotif?: string;
  /** Text density the set was designed around. Absent on older carousels. */
  visualMode?: CarouselVisualMode;
  /** Ties the rendered images together (`design_mockups.carousel_group_id`). */
  groupId: string;
  /** Medium picked for the whole set — mixing mediums breaks the set. */
  imageType: DesignImageType;
  slots: CarouselSlot[];
  /**
   * La historia que el usuario eligió antes de escribir una línea.
   *
   * Va aquí y no en una tabla nueva: el plan pertenece a este carrusel, y una segunda
   * fuente de verdad sobre lo mismo se desincroniza el día que alguien edita un slide.
   * Es la misma decisión que ya rige el resto de este objeto.
   *
   * Se persiste porque el guion se puede volver a pedir —cambia el objetivo, cambia la
   * guía— y sin el plan guardado ese segundo guion inventaría su propia estructura y el
   * set quedaría escrito contra dos historias distintas.
   *
   * Opcional: los carruseles anteriores al planificador no tienen ninguno, y los que se
   * generan sin elegir historia tampoco.
   */
  plan?: CarouselCreativePlan;
  /**
   * Fuente numérica estable del carrusel. Los beats proyectan subconjuntos de sus hechos;
   * los carruseles antiguos no la tienen y siguen leyendo `brief.documents`.
   */
  economicScenario?: CarouselEconomicScenario;
  /**
   * El resumen semántico del plan.
   *
   * Es lo que permite pedir "otra historia" más adelante sin volver a generar las
   * anteriores: el planificador compara contra digests, no contra planes completos.
   */
  planDigest?: CarouselPlanDigest;
  createdAt: string;
}

/**
 * A narrative shape for a carousel. The preset — not the agent — decides how
 * many slides there are and which ones carry brand elements, so adding
 * "mito vs realidad" or "3 pasos" later needs no change to the agent.
 */
export interface CarouselPreset {
  slug: string;
  name: string;
  description: string;
  /** One entry per slide, in reading order. Length = number of slides. */
  roles: CarouselSlideRole[];
  /**
   * Which slide reserves space for each brand element, addressed by role so the
   * mapping survives presets of different lengths. Omit an element to leave it off.
   *
   * This only reserves negative space in the prompt — nothing is composited by the
   * export, which would stamp a lockup on top of one mounted by hand. Mounting is
   * done per piece in the brand layer editor.
   *
   * The disclaimer rides the slide that makes the claim, not automatically the
   * last one: a legal note has to sit next to the number it qualifies.
   */
  brandPlacement: Partial<Record<CarouselBrandElement, CarouselSlideRole>>;
  /** How much text the pieces are designed around. */
  visualMode: CarouselVisualMode;
  /**
   * Si los beats se necesitan entre sí.
   *
   * El validador del plan asumía `chained` en todas las estructuras, y con eso castigaba
   * a este mismo checklist por hacer lo que sus propias reglas mandan: "los ítems son
   * INDEPENDIENTES entre sí, prohibido encadenarlos". Un preset cuyos beats son
   * independientes no puede declarar qué retoma del anterior, porque no retoma nada.
   */
  beatCoupling: PresetBeatCoupling;
  /**
   * Cómo se comporta la composición a lo largo del set.
   *
   * `repeated` y `progressive` son los casos donde compartir encuadre es la intención y
   * no un descuido: una lista se lee como serie porque sus fichas están compuestas
   * igual, y una cronología es la misma escena avanzando.
   */
  layoutPolicy: PresetLayoutPolicy;
  /** Qué hace el set con el copy semilla. */
  seedUsage: PresetSeedUsage;
  /** Quién es dueño de la última frase. */
  closingPolicy: PresetClosingPolicy;
  /**
   * How this structure is read, in the agent's own instructions.
   *
   * These rules used to live in the prompt as a single fixed block, and that block
   * described one thing: an argument chained across five slides, opening on the seed
   * headline. Every structure came out as that structure — a checklist written under
   * "los slides se leen como una sola oración cortada en cinco" is not a checklist.
   *
   * Only what is specific to the shape goes here. Compliance, line length, the
   * conditional on risk and the ban on invented product claims stay global: they
   * are true of every carousel we publish.
   */
  narrativeRules: string;
}

export const CAROUSEL_ROLE_LABELS: Record<CarouselSlideRole, string> = {
  tension: 'Tensión',
  shift: 'Qué cambia',
  risk: 'Qué riesgo',
  solution: 'Solución',
  cta: 'CTA',
  hook: 'Gancho',
  problem: 'Problema',
  example: 'Ejemplo',
  promise: 'Promesa',
  signal: 'Señal',
  moment: 'Momento',
  outcome: 'Resultado',
  close: 'Cierre',
};

/*
 * Aquí vivían `CAROUSEL_ROLE_BRIEFS` y `CAROUSEL_ROLE_LAYOUT_HINT`, las dos tablas del
 * camino sin Creative Plan. Se borraron cuando elegir historia pasó a ser obligatorio.
 *
 * Las dos eran hojas de respuestas indexadas por ROL: el brief dictaba el contenido de
 * la escena ("la escena repite: varias compras, varios documentos") y el layout dictaba
 * la composición. Con el contenido dictado por rol, tres rutas narrativas distintas
 * devolvían los mismos beats 3, 4 y 5 — el fallo que motivó toda esta fase.
 *
 * De dónde sale ahora cada cosa: el contenido lo declara el beat del plan, la redacción
 * la gobierna `SCRIPT_BEAT_RULES` en la edge function, y la composición viaja en
 * `beat.compositionFamily`, derivada de los cinco atributos del `CompositionSpec`.
 */

/** Cómo se lee un arco encadenado: el que usa el banco aprobado. */
const CHAINED_ARC_RULES = `1. El slide 1 lleva el headline semilla COMPLETO, casi tal cual. Ese texto ya lo aprobó el usuario: respétalo, no lo "mejores". Si son dos oraciones en contraste, van las dos en la misma línea — partir la antítesis entre dos niveles de texto mata el gancho.
2. Los slides se leen como UNA sola oración cortada en varias. Cada slide continúa el anterior y lo retoma ("Eso puede…", "Ese movimiento…", "Y con él…"). Leer uno solo, fuera de orden, deja la idea incompleta: eso es correcto en esta estructura.`;

/** Cómo se lee una lista: al revés que el arco, cada slide se sostiene solo. */
const CHECKLIST_RULES = `1. El slide 1 NO es el copy semilla. Es la portada de la lista y anuncia cuántos ítems son: "3 señales de que tu operación tiene exposición abierta". El copy semilla es la materia prima de los ítems, no el titular.
2. Los ítems son INDEPENDIENTES entre sí. Prohibido encadenarlos: ninguno empieza con "eso", "además", "y con él", "por eso". Cada uno se entiende sin haber leído los otros y se puede leer en cualquier orden. Esto es lo contrario de un arco argumental — si los ítems se necesitan entre sí, la lista está mal armada.
3. Cada ítem es una SITUACIÓN VERIFICABLE, no un argumento ni un consejo. "Facturas en dólares y presupuestas en pesos" sí. "Deberías revisar tu exposición" no.
4. Los ítems no se repiten ni se solapan: si dos describen lo mismo con otras palabras, sobra uno. Tienen que ser tres cosas distintas que pasan en la misma operación.
5. Los ítems comparten forma gramatical entre ellos — los tres arrancan igual, con el mismo tipo de sujeto y el mismo tiempo verbal. Eso es lo que hace que se lean como una lista y no como tres frases sueltas.
6. Los ítems también comparten LAYOUT y tipo de escena: cambia el objeto de cada uno, no la composición. Una lista donde cada ficha está encuadrada distinto se lee como tres piezas sueltas.`;

/** Cómo se lee una cronología: los slides son fechas, no argumentos. */
const TIMELINE_RULES = `1. El slide 1 NO es el copy semilla: es la PRIMERA FECHA de la operación. El copy semilla dice de qué trata la cronología; tú la conviertes en momentos.
2. Cada slide es UN MOMENTO con nombre temporal en el headline: "El día que cotizas", "Sesenta días después", "El día del pago". El lector avanza en el tiempo, no en un razonamiento.
3. Los momentos van en ORDEN CRONOLÓGICO y la distancia entre ellos se nombra. Un salto sin decir cuánto tiempo pasó rompe la única mecánica de esta estructura.
4. Es la MISMA operación en los N momentos. No cambies de proveedor, de producto ni de monto entre slides: lo único que avanza es la fecha, y lo que eso deja abierto o cerrado.
5. No argumentes: REPORTA. Cada slide dice qué se sabe y qué todavía no en esa fecha. La conclusión vive únicamente en el slide de resultado.
6. Prohibido el condicional especulativo en los momentos intermedios ("podría", "tal vez"). En una fecha las cosas ya pasaron o todavía no han pasado, y eso es más fuerte que una hipótesis.
7. Los momentos comparten LAYOUT y escena: el mismo expediente, el mismo encuadre, lo que cambia es la fecha y lo que el documento ya dice. Cambiar la composición entre fechas rompe la sensación de que es la misma operación avanzando.`;

export const CAROUSEL_PRESETS: CarouselPreset[] = [
  {
    slug: 'tension-shift-risk-solution-cta',
    name: 'Tensión → Qué cambia → Riesgo → Solución → CTA',
    description:
      'Los cinco tiempos del banco de copys aprobado: una sola línea por slide y el CTA solo al cierre.',
    roles: ['tension', 'shift', 'risk', 'solution', 'cta'],
    // Logo on the cover: it is the only slide everyone sees in the feed.
    // No disclaimer: the legal note is composited outside this flow when the piece
    // is published, so reserving space for one here would leave an empty strip.
    brandPlacement: { logo: 'tension' },
    visualMode: 'EDITORIAL_FULL_TEXT',
    beatCoupling: 'chained',
    layoutPolicy: 'varied',
    seedUsage: 'cover',
    closingPolicy: 'cta',
    narrativeRules: CHAINED_ARC_RULES,
  },
  {
    slug: 'hook-problem-example-solution',
    name: 'Gancho → Problema → Ejemplo → Solución',
    description:
      'Arco de 4 slides con headline y body por slide. Cierra con el CTA en el último.',
    roles: ['hook', 'problem', 'example', 'solution'],
    brandPlacement: { logo: 'hook' },
    visualMode: 'EDITORIAL_FULL_TEXT',
    beatCoupling: 'chained',
    layoutPolicy: 'varied',
    seedUsage: 'cover',
    closingPolicy: 'cta',
    narrativeRules: CHAINED_ARC_RULES,
  },
  {
    slug: 'checklist-3-senales',
    name: 'Checklist — 3 señales',
    description:
      'Portada con la promesa, tres señales independientes y un cierre. El lector se autodiagnostica y los slides se pueden leer en cualquier orden.',
    roles: ['promise', 'signal', 'signal', 'signal', 'close'],
    brandPlacement: { logo: 'promise' },
    visualMode: 'EDITORIAL_FULL_TEXT',
    // Los ítems no se encadenan y comparten composición a propósito: las dos cosas
    // están en CHECKLIST_RULES y ahora también en un campo que el código puede leer.
    beatCoupling: 'independent',
    layoutPolicy: 'repeated',
    seedUsage: 'source_material',
    closingPolicy: 'idea',
    narrativeRules: CHECKLIST_RULES,
  },
  {
    slug: 'cronologia-operacion',
    name: 'Cronología de una operación',
    description:
      'Tres fechas de la misma operación y un resultado. El lector sigue un caso en el tiempo, no un argumento.',
    roles: ['moment', 'moment', 'moment', 'outcome', 'close'],
    brandPlacement: { logo: 'moment' },
    visualMode: 'EDITORIAL_FULL_TEXT',
    // Los momentos avanzan en el tiempo y comparten escena: "el mismo expediente, el
    // mismo encuadre, lo que cambia es la fecha".
    beatCoupling: 'temporal',
    layoutPolicy: 'progressive',
    seedUsage: 'source_material',
    closingPolicy: 'idea',
    narrativeRules: TIMELINE_RULES,
  },
];

export const DEFAULT_CAROUSEL_PRESET_SLUG = 'tension-shift-risk-solution-cta';

export function getCarouselPreset(slug: string): CarouselPreset {
  return (
    CAROUSEL_PRESETS.find((p) => p.slug === slug) ?? CAROUSEL_PRESETS[0]
  );
}

// ---------------------------------------------------------------------------
// Mecanismo comercial derivado del copy
// ---------------------------------------------------------------------------

/**
 * Ángulo del copy → mecanismo comercial, para la rama costos.
 *
 * El mecanismo filtra las rutas narrativas ANTES del plan (ver
 * `carouselStoryRegistry.resolveCompatibleRoutes`). Cuando el panel lo dejaba fijo en
 * `quote_comparison`, casi toda la rama se contaba como "comparar cotizaciones" aunque
 * el copy hablara de otra cosa: un copy de anatomía de costo o de costo+velocidad
 * terminaba en la ruta de comparación porque su ruta propia nunca entraba al menú.
 *
 * La clave es el `angle_tag` del copy (vocabulario controlado del banco), no el label.
 * Un ángulo no listado cae al fallback de la rama, que conserva el comportamiento
 * previo. El usuario siempre puede sobreescribir el chip a mano.
 */
export const COSTOS_ANGLE_COMMERCIAL_INTENT: Readonly<
  Record<string, CarouselCommercialIntent>
> = {
  // Comparar una segunda cotización del mismo pago.
  segunda_cotizacion: 'quote_comparison',
  diversificacion_de_proveedores: 'quote_comparison',
  proveedor_habitual: 'quote_comparison',
  // Costo y tiempo se deciden juntos. `comparacion_integral` entra aquí porque nombra
  // el tiempo como variable de decisión ("tipo de cambio, comisión y tiempo").
  costo_velocidad: 'cost_plus_speed',
  comparacion_integral: 'cost_plus_speed',
  // El costo como componente: anatomía, acumulación, margen, componente cambiario.
  costo_total_de_importacion: 'cost_component',
  impacto_acumulado: 'cost_component',
  impacto_anual: 'cost_component',
  escala_e_impacto_acumulado: 'cost_component',
  costo_cambiario: 'cost_component',
  proteccion_margen: 'cost_component',
  simplificacion_operativa: 'cost_component',
  diferencias_por_mercado: 'cost_component',
  diferencias_por_mercado_y_moneda: 'cost_component',
};

/**
 * Mecanismo comercial inicial de un carrusel, derivado de la rama y del ángulo del copy.
 *
 * Sustituye al default fijo por rama: coberturas siempre `forward`; costos lee el ángulo
 * del copy y cae a `quote_comparison` si el ángulo no está mapeado; el resto,
 * `cost_component`.
 */
export function deriveCarouselCommercialIntent(
  branchSlug: string | null | undefined,
  angleTag: string | null | undefined,
): CarouselCommercialIntent {
  const branch = (branchSlug ?? '').toLowerCase();
  if (branch.includes('cobertura')) return 'forward';
  if (branch.includes('costo')) {
    const key = (angleTag ?? '').trim().toLowerCase();
    return COSTOS_ANGLE_COMMERCIAL_INTENT[key] ?? 'quote_comparison';
  }
  return 'cost_component';
}

// ---------------------------------------------------------------------------
// Illustrative FX figures
// ---------------------------------------------------------------------------

/**
 * Assumptions behind the numbers a carousel is allowed to show.
 *
 * These exist because the figures have to be arithmetically coherent: a piece
 * showing "USD 8,750" next to "MXN 157,980" is implicitly quoting a rate of
 * 18.06 that nobody chose, and anyone who divides catches it. The rate is an
 * input rather than something the model picks, and every other number is derived
 * from it in code — language models are unreliable at arithmetic, and here the
 * arithmetic IS the message.
 */
export interface CarouselFxAssumptions {
  /** Illustrative rate, set by the user. Never presented as a market quote. */
  baseRate: number;
  /** Segunda tasa editable para comparar cotizaciones simultáneas. */
  comparisonRate?: number;
  /** USD amount of the illustrative operation. */
  amountUsd: number;
  /**
   * Drift of each later moment against the BASE rate, in percent — not against
   * the previous one. Small on purpose: the point is that a small movement
   * repeated adds up, not that the purchases got bigger.
   */
  driftPct: number[];
  /** Markup objetivo sobre costo importado. Es la semántica real del cálculo. */
  markupPct?: number;
  /**
   * @deprecated Alias persistido anterior. También representaba markup sobre costo,
   * no margen bruto; se lee solo para compatibilidad.
   */
  marginPct?: number;
  /**
   * Tasa expuesta explícita del escenario forward. Cuando está presente, el momento
   * expuesto usa esta tasa tal cual en vez de derivarla de `driftPct`: es la tasa que el
   * usuario cree posible a `daysAhead` si no cubre.
   */
  exposedRate?: number;
  /**
   * Precio de venta comprometido, en MXN, dado por el usuario. Presente => el forward
   * cuenta la historia de margen; ausente => solo el delta de costo.
   *
   * Su semántica depende de `direction`: en importación es el PRECIO DE VENTA (ingreso
   * fijo); en exportación es el COSTO fijo. El motor calcula el margen en consecuencia.
   */
  salePriceMxn?: number;
  /** Horizonte del escenario forward, en días. Solo etiqueta, nunca fecha de calendario. */
  daysAhead?: number;
  /**
   * Dirección de la operación forward. Importación (debes USD, riesgo = dólar sube) o
   * exportación (te pagan USD, riesgo = dólar baja). Cambia qué es fijo y qué variable, y
   * el vocabulario (costo ↔ ingreso). Por defecto 'import'.
   */
  direction?: CarouselFxDirection;
}

/** Dirección de la operación forward. */
export type CarouselFxDirection = 'import' | 'export';

/**
 * Margen objetivo cuando el llamador no declara ninguno.
 *
 * 35% sobre costo es un margen de reventa creíble para un importador de producto
 * terminado, y está elegido para que la historia funcione: con un margen muy alto, un
 * movimiento del 2% en el costo no se nota en el cuadro y la pieza no demuestra nada; con
 * uno muy bajo el margen queda casi en cero y se lee como una afirmación de pérdida, que
 * el kit editorial prohíbe.
 */
export const DEFAULT_MARKUP_PCT = 35;
/** @deprecated Nombre anterior; se conserva para callers persistidos. */
export const DEFAULT_MARGIN_PCT = DEFAULT_MARKUP_PCT;

// ---------------------------------------------------------------------------
// El monto de la operación ilustrativa
// ---------------------------------------------------------------------------

/**
 * Piso y techo de una operación ilustrativa, en USD.
 *
 * Existían de facto en un solo valor: `amountUsd: 10000`, en todos los sets de todas
 * las industrias. Diez mil dólares es una compra creíble de mobiliario y es una cifra
 * absurda para una línea de producción, así que la pieza se leía como un ejemplo de
 * plantilla en la mitad de los casos.
 */
export const MIN_ILLUSTRATIVE_USD = 10_000;
export const MAX_ILLUSTRATIVE_USD = 150_000;

/**
 * El techo sube solo para obra e infraestructura.
 *
 * Es la excepción explícita: un proyecto de planta o de generación no se cotiza en el
 * mismo orden de magnitud que un contenedor de producto terminado, y forzarlo al techo
 * general produciría el mismo problema al revés.
 */
export const MAX_MEGA_PROJECT_USD = 250_000;

/** Sin acentos ni mayúsculas, para emparejar el nombre de la industria. */
function normalizeForMatch(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/**
 * Orden de magnitud de una compra, por industria.
 *
 * Bandas y no valores exactos: lo que la pieza necesita es una cifra PLAUSIBLE para
 * quien la lee, y dentro de la banda cualquiera lo es. Lo que no es plausible es la
 * misma cifra para todos.
 *
 * Las bandas van de más específica a más general y se evalúan en orden, porque
 * "maquinaria para planta solar" tiene que caer en obra y no en maquinaria.
 */
const ORDER_BANDS: { match: RegExp; min: number; max: number; label: string }[] = [
  {
    match: /obra|infraestructura|planta|construccion|energia|solar|eolic|mineria|refineria/,
    min: 90_000,
    max: MAX_MEGA_PROJECT_USD,
    label: 'proyecto de infraestructura',
  },
  {
    match: /maquinaria|industrial|equipo pesado|manufactura|cnc|torno|inyeccion|linea de produccion/,
    min: 55_000,
    max: MAX_ILLUSTRATIVE_USD,
    label: 'maquinaria industrial',
  },
  { match: /autoparte|automotriz|refaccion|ensamble/, min: 30_000, max: 90_000, label: 'autopartes' },
  {
    match: /electronic|componente|tecnolog|semiconductor|hardware|computo/,
    min: 25_000,
    max: 80_000,
    label: 'electrónica',
  },
  {
    match: /farmac|medic|salud|laboratorio|hospital/,
    min: 20_000,
    max: 70_000,
    label: 'insumos médicos',
  },
  { match: /alimento|agro|bebida|abarrote|empaque/, min: 18_000, max: 55_000, label: 'alimentos' },
  {
    match: /mueble|mobiliario|decorac|interiorismo|hogar/,
    min: 15_000,
    max: 45_000,
    label: 'mobiliario',
  },
  { match: /textil|ropa|calzado|moda|confeccion/, min: 12_000, max: 40_000, label: 'textil' },
];

/** Cuando la industria no se reconoce o no hay ninguna. */
const DEFAULT_ORDER_BAND = {
  min: 15_000,
  max: 60_000,
  label: 'importacion general',
} as const;

function orderBandFor(industryName?: string | null) {
  const name = normalizeForMatch(industryName?.trim() ?? '');
  if (!name) return DEFAULT_ORDER_BAND;
  return ORDER_BANDS.find((b) => b.match.test(name)) ?? DEFAULT_ORDER_BAND;
}

/**
 * Hash estable de una cadena. FNV-1a de 32 bits.
 *
 * Determinista a propósito, y es el punto: el mismo copy tiene que producir siempre la
 * misma cifra. Con un aleatorio, regenerar los prompts de un set ya renderizado
 * cambiaría los montos y dos slides del mismo carrusel cotizarían operaciones distintas.
 */
function stableSeed(text: string): number {
  let hash = 2166136261;
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return Math.abs(hash | 0);
}

/**
 * El monto de la operación ilustrativa, deducido de la historia.
 *
 * Reemplaza al 10,000 fijo. La industria decide el orden de magnitud y el copy semilla
 * decide dónde cae dentro de esa banda, así que dos piezas de la misma industria no
 * cotizan lo mismo y la misma pieza cotiza siempre igual.
 *
 * Sigue siendo un valor ILUSTRATIVO y editable en el panel: esto solo cambia de qué
 * parte se arranca. Una cotización inventada no se presenta nunca como vigente ni como
 * oficial — eso ya lo dicen los prompts, y no cambia porque el monto ahora sea creíble.
 *
 * Se redondea a múltiplos de 500 porque una cotización real no termina en 37,412: un
 * monto con esa precisión invita a buscarle una fuente que no existe.
 */
export function illustrativeAmountUsd(params: {
  industryName?: string | null;
  /** El copy semilla. Es lo que hace que dos piezas de la misma industria difieran. */
  seed?: string | null;
}): number {
  const band = orderBandFor(params.industryName);
  const span = Math.max(0, band.max - band.min);
  const seed = stableSeed(params.seed?.trim() || band.label);

  const raw = band.min + (span === 0 ? 0 : seed % (span + 1));
  const rounded = Math.round(raw / 500) * 500;

  return Math.min(Math.max(rounded, MIN_ILLUSTRATIVE_USD), band.max);
}

/**
 * Standard illustrative case: USD 10,000 at 17.20, drifting +1% and +2%.
 *
 * One ceiling for the whole carousel (+2%) rather than a different percentage per
 * slide — the reader is following one mechanism, and unrelated percentages make it
 * look like unrelated examples. 2% keeps it plausible: a movement small enough to
 * be ignored and large enough to matter when it repeats. The +1% exists only so
 * the three-purchase comparison has a middle step.
 */
export const DEFAULT_CAROUSEL_FX: CarouselFxAssumptions = {
  baseRate: 17.2,
  /** Segunda cotización simultánea; nunca se interpreta como una tasa futura. */
  comparisonRate: 17.54,
  /**
   * Solo el respaldo. El monto real lo deduce `illustrativeAmountUsd` de la industria y
   * del copy: este valor es lo que se usa cuando el llamador no pasa nada, y quedarse en
   * él en producción es el fallo que la deducción vino a quitar.
   */
  amountUsd: 10000,
  /** Against the base: +1% and +2%. Not compounded — see `computeCarouselFx`. */
  driftPct: [1, 2],
  markupPct: DEFAULT_MARKUP_PCT,
};

/** One moment of the illustrative operation, with its text ready to render. */
export interface CarouselFxMoment {
  rate: number;
  amountUsd: number;
  amountMxn: number;
  /** Difference in MXN against the first moment. Zero on the first. */
  deltaMxn: number;
  /** Drift against the first moment, in percent. Zero on the first. */
  deltaPct: number;
  labels: {
    rate: string;
    usd: string;
    mxn: string;
    delta: string;
    pct: string;
  };
}

/** Thousands separators and two decimals, without depending on ICU. */
function formatAmount(value: number): string {
  const [int, dec] = Math.abs(value).toFixed(2).split('.');
  const grouped = int.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  return `${value < 0 ? '-' : ''}${grouped}.${dec}`;
}

/**
 * Derive the moments of the illustrative operation.
 *
 * The rate is rounded to two decimals BEFORE the multiplication, on purpose: the
 * piece shows both the rate and the total, so they have to agree when a reader
 * multiplies them by hand. Computing with full precision and rounding only for
 * display would print 17.47 next to 174,730 — off by 30 pesos and wrong to
 * anyone checking.
 *
 * Every drift is measured against the BASE moment, not against the previous one.
 * "+2%" has to mean one thing: with compounding, the third moment of a 1%/2% set
 * is +3.02% against the base while the label says +2%, and a piece that shows a
 * percentage next to the numbers it describes cannot afford that ambiguity.
 */
export function computeCarouselFx(a: CarouselFxAssumptions): CarouselFxMoment[] {
  // Every product is rounded to cents. Without this, 17.33 * 10000 lands on
  // 173299.99999999997 and the piece prints a total that is a cent short of the
  // multiplication it displays.
  const toCents = (n: number) => Math.round(n * 100) / 100;

  const baseRate = toCents(a.baseRate);
  const base = toCents(baseRate * a.amountUsd);

  const moment = (rate: number): CarouselFxMoment => {
    const rounded = toCents(rate);
    const amountMxn = toCents(rounded * a.amountUsd);
    const deltaMxn = toCents(amountMxn - base);
    const deltaPct = base === 0 ? 0 : Math.round((deltaMxn / base) * 1000) / 10;
    return {
      rate: rounded,
      amountUsd: a.amountUsd,
      amountMxn,
      deltaMxn,
      deltaPct,
      labels: {
        rate: formatAmount(rounded).replace(/,/g, ''),
        usd: `USD ${formatAmount(a.amountUsd)}`,
        mxn: `MXN ${formatAmount(amountMxn)}`,
        delta: deltaMxn === 0 ? '' : `+MXN ${formatAmount(deltaMxn)}`,
        pct: deltaPct === 0 ? '' : `+${deltaPct.toFixed(1)}%`,
      },
    };
  };

  /*
   * Tasa expuesta explícita: el forward. Dos momentos exactos —la pactada y la posible—
   * en vez de una deriva sintética. El usuario da las dos tasas; el código no inventa
   * ninguna. Si la expuesta iguala a la pactada, sigue habiendo dos momentos (delta cero),
   * porque la historia es la comparación, no el movimiento.
   */
  if (a.exposedRate !== undefined) {
    return [moment(baseRate), moment(a.exposedRate)];
  }

  return [0, ...a.driftPct].map((drift) => moment(baseRate * (1 + drift / 100)));
}

/** One line of a document in the scene: a field name and its exact value. */
export interface CarouselFigureField {
  label: string;
  value: string;
  /** Meaning of the value, which resolves its colour. Omitted = neutral navy. */
  colorRole?: CarouselColorRole;
}

/**
 * A document in the scene, with every visible value already decided.
 *
 * This replaced a flat list of labels, and the reason is worth keeping: given
 * `["TOTAL USD 10,000.00", "TIPO DE CAMBIO 18.38", "TIPO DE CAMBIO 18.56", ...]`
 * the image model has no way to know which value belongs to which card, so it put
 * the same numbers on all three and pulled a stray "+4.0%" out of the pile. Data
 * for several documents has to be shaped like several documents.
 */
export interface CarouselFigureDocument {
  /** 'HOY', 'PAGO', 'COMPRA 1'. Doubles as the stamp on the document. */
  label: string;
  /** 'COTIZACIÓN', 'FACTURA'. The document has to look like something. */
  kind: string;
  date?: string;
  fields: CarouselFigureField[];
  /** Always present: a quote explaining a cost without a TOTAL reads unfinished. */
  total: CarouselFigureField;
}

/** Which numeric story a slide is telling. */
export type CarouselFigureScenario = 'two_moment' | 'repeated_purchases';

const MONTHS_ES = [
  'ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN',
  'JUL', 'AGO', 'SEP', 'OCT', 'NOV', 'DIC',
];

/** '20 JUN 2026' — the format these documents print. */
export function formatFigureDate(date: Date): string {
  return `${String(date.getDate()).padStart(2, '0')} ${MONTHS_ES[date.getMonth()]} ${date.getFullYear()}`;
}

function shiftDays(base: Date, days: number): Date {
  const next = new Date(base);
  next.setDate(next.getDate() + days);
  return next;
}

/**
 * Turn the computed moments into the documents a slide renders.
 *
 * The field set is identical across documents of the same scenario, in the same
 * order, because that is what makes a comparison readable: the eye finds the one
 * value that changed instead of re-reading two different layouts. The only
 * asymmetry allowed is the variation line, which the base case does not have
 * because there is nothing yet to vary against.
 *
 * Dates are derived from `today` rather than hardcoded so the pieces do not carry
 * a stale year.
 *
 * The two-moment case takes the first and LAST moment, skipping the middle steps.
 * Its claim is what the movement costs by payment day, so it needs the full gap
 * (17.20 → 17.54); the intermediate +1% exists only for the three-purchase
 * comparison, and using it here would show a smaller number than the story states.
 */
export function buildFigureDocuments(
  scenario: CarouselFigureScenario,
  moments: CarouselFxMoment[],
  today: Date = new Date(),
): CarouselFigureDocument[] {
  const labels = scenario === 'two_moment'
    ? ['HOY', 'PAGO']
    : ['COMPRA 1', 'COMPRA 2', 'COMPRA 3'];
  const dayOffsets = scenario === 'two_moment' ? [0, 60] : [0, 35, 70];

  const selected = scenario === 'two_moment' && moments.length > 1
    ? [moments[0], moments[moments.length - 1]]
    : moments.slice(0, labels.length);

  return selected.map((m, i) => {
    const fields: CarouselFigureField[] = [
      // Navy: the obligation is neither the benefit nor the risk, and it is the
      // value that must read as identical across every document.
      { label: 'TOTAL USD', value: m.labels.usd.replace('USD ', '') },
      {
        label: 'TIPO DE CAMBIO',
        value: m.labels.rate,
        colorRole: i === 0 ? 'control' : 'risk',
      },
      {
        label: 'COSTO MXN',
        value: m.labels.mxn.replace('MXN ', ''),
        colorRole: i === 0 ? 'control' : 'risk',
      },
    ];

    if (m.labels.pct) {
      fields.push({ label: 'VARIACIÓN', value: m.labels.pct, colorRole: 'risk' });
    }

    return {
      label: labels[i],
      kind: 'COTIZACIÓN',
      date: formatFigureDate(shiftDays(today, dayOffsets[i])),
      fields,
      total: {
        label: 'TOTAL',
        value: m.labels.mxn.replace('MXN ', ''),
        colorRole: i === 0 ? undefined : 'risk',
      },
    };
  });
}

/**
 * What the repetition slide is actually about: the differences adding up.
 *
 * Each purchase costs more in pesos than the first one did, and the slide's claim is
 * that those gaps compound. That total is the number the piece needs — showing three
 * growing totals without it leaves the reader to do the addition.
 */
export function accumulatedFxImpact(moments: CarouselFxMoment[]): {
  amount: number;
  label: string;
} {
  const amount = Math.round(moments.reduce((sum, m) => sum + m.deltaMxn, 0) * 100) / 100;
  return {
    amount,
    label: amount === 0 ? '' : `+MXN ${formatAmount(amount)}`,
  };
}

const toCents = (value: number): number => Math.round(value * 100) / 100;
const toTenth = (value: number): number => Math.round(value * 10) / 10;

/*
 * Etiquetas del forward: el lenguaje del negocio, no el técnico, y según la dirección.
 *
 * Importas: debes USD, lo VARIABLE es tu COSTO y lo fijo tu precio de venta; el riesgo es
 * que el dólar SUBA. Exportas: te pagan USD, lo VARIABLE es tu INGRESO y lo fijo tu costo;
 * el riesgo es que el dólar BAJE. La misma mecánica, vocabulario invertido.
 */
const FORWARD_FACT_LABELS_IMPORT: Partial<Record<CarouselEconomicFactKey, string>> = {
  base_rate: 'TC PRESUPUESTADO',
  exposed_rate: 'TC AL PAGO',
  base_cost_mxn: 'COSTO PRESUPUESTADO',
  exposed_cost_mxn: 'COSTO AL PAGO',
  cost_delta_mxn: 'AUMENTO DE COSTO',
  cost_delta_pct: 'VARIACIÓN',
  base_gross_profit_mxn: 'UTILIDAD PRESUPUESTADA',
  exposed_gross_profit_mxn: 'UTILIDAD AL PAGO',
  base_gross_margin_pct: 'MARGEN PRESUPUESTADO',
  exposed_gross_margin_pct: 'MARGEN AL PAGO',
  sale_price_mxn: 'PRECIO DE VENTA FIJO',
};

const FORWARD_FACT_LABELS_EXPORT: Partial<Record<CarouselEconomicFactKey, string>> = {
  base_rate: 'TC PRESUPUESTADO',
  exposed_rate: 'TC AL COBRO',
  base_cost_mxn: 'INGRESO PRESUPUESTADO',
  exposed_cost_mxn: 'INGRESO AL COBRO',
  cost_delta_mxn: 'CAÍDA DE INGRESO',
  cost_delta_pct: 'VARIACIÓN',
  base_gross_profit_mxn: 'UTILIDAD PRESUPUESTADA',
  exposed_gross_profit_mxn: 'UTILIDAD AL COBRO',
  base_gross_margin_pct: 'MARGEN PRESUPUESTADO',
  exposed_gross_margin_pct: 'MARGEN AL COBRO',
  sale_price_mxn: 'COSTO FIJO',
};

/*
 * En la solución/cierre, la MISMA base cambia de nombre: ya no es "lo presupuestado", es
 * "lo que el forward dejó pactado". Mismo número, otra lectura, porque el rol del beat es
 * la resolución. Es la única forma de que un solo escenario cuente el problema y su
 * solución sin inventar cifras nuevas.
 */
const FORWARD_RESOLUTION_LABELS_IMPORT: Partial<Record<CarouselEconomicFactKey, string>> = {
  base_rate: 'FORWARD PACTADO',
  base_cost_mxn: 'COSTO FINAL',
  base_gross_profit_mxn: 'UTILIDAD DEFINIDA',
  base_gross_margin_pct: 'MARGEN PROTEGIDO',
};

const FORWARD_RESOLUTION_LABELS_EXPORT: Partial<Record<CarouselEconomicFactKey, string>> = {
  base_rate: 'FORWARD PACTADO',
  base_cost_mxn: 'INGRESO FINAL',
  base_gross_profit_mxn: 'UTILIDAD DEFINIDA',
  base_gross_margin_pct: 'MARGEN PROTEGIDO',
};

const forwardFactLabels = (direction: CarouselFxDirection) =>
  direction === 'export' ? FORWARD_FACT_LABELS_EXPORT : FORWARD_FACT_LABELS_IMPORT;
const forwardResolutionLabels = (direction: CarouselFxDirection) =>
  direction === 'export' ? FORWARD_RESOLUTION_LABELS_EXPORT : FORWARD_RESOLUTION_LABELS_IMPORT;

/** Construye una sola columna vertebral financiera para todo el carrusel. */
export function buildCarouselEconomicScenario(
  scenarioId: Exclude<CarouselFigureScenarioId, 'none'>,
  assumptions: CarouselFxAssumptions,
  now: Date = new Date(),
): CarouselEconomicScenario {
  const moments = computeCarouselFx(assumptions);
  const base = moments[0];
  const exposed = moments[moments.length - 1] ?? base;
  const quoteARate = toCents(base.rate);
  const quoteBRate = toCents(assumptions.comparisonRate ?? exposed.rate);
  const quoteACostMxn = toCents(quoteARate * assumptions.amountUsd);
  const quoteBCostMxn = toCents(quoteBRate * assumptions.amountUsd);
  const quoteDifferenceMxn = toCents(quoteBCostMxn - quoteACostMxn);
  const quoteDifferencePct = quoteACostMxn === 0
    ? 0
    : toTenth((quoteDifferenceMxn / quoteACostMxn) * 100);
  const markupPct = Math.min(
    Math.max(assumptions.markupPct ?? assumptions.marginPct ?? DEFAULT_MARKUP_PCT, MIN_MARGIN_PCT),
    MAX_MARGIN_PCT,
  );
  /*
   * Precio de venta: absoluto si el usuario lo dio (forward), si no derivado del markup.
   * Es el mismo criterio que la hoja de margen renderizada, para que el preview y el
   * escenario persistido no discrepen.
   */
  const salePriceMxn = assumptions.salePriceMxn !== undefined && assumptions.salePriceMxn > 0
    ? toCents(assumptions.salePriceMxn)
    : toCents(base.amountMxn * (1 + markupPct / 100));
  /*
   * Utilidad = ingreso − costo, siempre. Lo que cambia con la dirección es CUÁL lado es
   * fijo y cuál cruza el tipo de cambio:
   *   - Importas: el ingreso (precio de venta) es fijo; el costo del pago es variable.
   *   - Exportas: el costo es fijo; el ingreso del cobro es variable.
   * El margen se mide siempre sobre el ingreso.
   */
  const isExport = (assumptions.direction ?? 'import') === 'export';
  const profitAt = (variableMxn: number): number =>
    toCents(isExport ? variableMxn - salePriceMxn : salePriceMxn - variableMxn);
  const marginAt = (profit: number, variableMxn: number): number => {
    const revenue = isExport ? variableMxn : salePriceMxn;
    return revenue === 0 ? 0 : toTenth((profit / revenue) * 100);
  };
  const baseGrossProfitMxn = profitAt(base.amountMxn);
  const exposedGrossProfitMxn = profitAt(exposed.amountMxn);
  const baseGrossMarginPct = marginAt(baseGrossProfitMxn, base.amountMxn);
  const exposedGrossMarginPct = marginAt(exposedGrossProfitMxn, exposed.amountMxn);
  const accumulatedImpactMxn = accumulatedFxImpact(moments).amount;

  const allFacts: CarouselEconomicFact[] = [
    { key: 'operation_usd', label: 'OPERACIÓN', value: base.amountUsd, formattedValue: `USD ${formatAmount(base.amountUsd)}`, unit: 'USD', state: 'base' },
    { key: 'base_rate', label: 'TIPO DE CAMBIO BASE', value: base.rate, formattedValue: formatAmount(base.rate).replace(/,/g, ''), unit: 'rate', state: 'base', colorRole: 'control' },
    { key: 'exposed_rate', label: 'TIPO DE CAMBIO EXPUESTO', value: exposed.rate, formattedValue: formatAmount(exposed.rate).replace(/,/g, ''), unit: 'rate', state: 'exposed', colorRole: 'risk' },
    { key: 'base_cost_mxn', label: 'COSTO BASE', value: base.amountMxn, formattedValue: `MXN ${formatAmount(base.amountMxn)}`, unit: 'MXN', state: 'base', colorRole: 'control' },
    { key: 'exposed_cost_mxn', label: 'COSTO EXPUESTO', value: exposed.amountMxn, formattedValue: `MXN ${formatAmount(exposed.amountMxn)}`, unit: 'MXN', state: 'exposed', colorRole: 'risk' },
    { key: 'cost_delta_mxn', label: 'DIFERENCIA DE COSTO', value: exposed.deltaMxn, formattedValue: `${exposed.deltaMxn >= 0 ? '+' : ''}MXN ${formatAmount(exposed.deltaMxn)}`, unit: 'MXN', state: 'delta', colorRole: 'risk' },
    { key: 'cost_delta_pct', label: 'VARIACIÓN DEL COSTO', value: exposed.deltaPct, formattedValue: `${exposed.deltaPct >= 0 ? '+' : ''}${exposed.deltaPct.toFixed(1)}%`, unit: 'percent', state: 'delta', colorRole: 'risk' },
    { key: 'quote_a_rate', label: 'TIPO DE CAMBIO XENDING', value: quoteARate, formattedValue: formatAmount(quoteARate).replace(/,/g, ''), unit: 'rate', state: 'base', colorRole: 'control' },
    { key: 'quote_b_rate', label: 'TIPO DE CAMBIO OTRA COTIZACIÓN', value: quoteBRate, formattedValue: formatAmount(quoteBRate).replace(/,/g, ''), unit: 'rate', state: 'derived' },
    { key: 'quote_a_cost_mxn', label: 'CONVERSIÓN CON XENDING', value: quoteACostMxn, formattedValue: `MXN ${formatAmount(quoteACostMxn)}`, unit: 'MXN', state: 'base', colorRole: 'control' },
    { key: 'quote_b_cost_mxn', label: 'CONVERSIÓN CON OTRA COTIZACIÓN', value: quoteBCostMxn, formattedValue: `MXN ${formatAmount(quoteBCostMxn)}`, unit: 'MXN', state: 'derived' },
    { key: 'quote_difference_mxn', label: 'DIFERENCIA DE CONVERSIÓN', value: quoteDifferenceMxn, formattedValue: `${quoteDifferenceMxn >= 0 ? '+' : ''}MXN ${formatAmount(quoteDifferenceMxn)}`, unit: 'MXN', state: 'delta' },
    { key: 'quote_difference_pct', label: 'DIFERENCIA PORCENTUAL', value: quoteDifferencePct, formattedValue: `${quoteDifferencePct >= 0 ? '+' : ''}${quoteDifferencePct.toFixed(1)}%`, unit: 'percent', state: 'delta' },
    { key: 'sale_price_mxn', label: 'PRECIO DE VENTA FIJO', value: salePriceMxn, formattedValue: `MXN ${formatAmount(salePriceMxn)}`, unit: 'MXN', state: 'defined' },
    { key: 'base_gross_profit_mxn', label: 'UTILIDAD BRUTA BASE', value: baseGrossProfitMxn, formattedValue: `MXN ${formatAmount(baseGrossProfitMxn)}`, unit: 'MXN', state: 'base', colorRole: 'control' },
    { key: 'exposed_gross_profit_mxn', label: 'UTILIDAD BRUTA EXPUESTA', value: exposedGrossProfitMxn, formattedValue: `MXN ${formatAmount(exposedGrossProfitMxn)}`, unit: 'MXN', state: 'exposed', colorRole: 'risk' },
    { key: 'base_gross_margin_pct', label: 'MARGEN BRUTO BASE', value: baseGrossMarginPct, formattedValue: `${baseGrossMarginPct.toFixed(1)}%`, unit: 'percent', state: 'base', colorRole: 'control' },
    { key: 'exposed_gross_margin_pct', label: 'MARGEN BRUTO EXPUESTO', value: exposedGrossMarginPct, formattedValue: `${exposedGrossMarginPct.toFixed(1)}%`, unit: 'percent', state: 'exposed', colorRole: 'risk' },
    { key: 'accumulated_impact_mxn', label: 'IMPACTO ACUMULADO', value: accumulatedImpactMxn, formattedValue: `${accumulatedImpactMxn >= 0 ? '+' : ''}MXN ${formatAmount(accumulatedImpactMxn)}`, unit: 'MXN', state: 'delta', colorRole: 'risk' },
    { key: 'defined_cost_mxn', label: 'COSTO DEFINIDO', value: base.amountMxn, formattedValue: `MXN ${formatAmount(base.amountMxn)}`, unit: 'MXN', state: 'defined', colorRole: 'control' },
  ];
  const allowed = new Set(CAROUSEL_SCENARIO_FACT_KEYS[scenarioId]);

  /*
   * En forward, el margen es opcional: sin precio de venta, la historia es solo el delta
   * de costo. Se quitan los hechos de margen del set permitido para que ni el escenario
   * ni el validador esperen algo que el usuario no pidió.
   */
  const dropForwardMargin =
    scenarioId === 'forward_protection' &&
    !(assumptions.salePriceMxn !== undefined && assumptions.salePriceMxn > 0);
  const marginKeys = new Set<CarouselEconomicFactKey>(CAROUSEL_FORWARD_MARGIN_FACT_KEYS);

  return {
    version: 1,
    scenarioId,
    qualifier: 'ESCENARIO ILUSTRATIVO',
    assumptions: {
      baseRate: assumptions.baseRate,
      comparisonRate: assumptions.comparisonRate,
      exposedRate: assumptions.exposedRate,
      salePriceMxn: dropForwardMargin ? undefined : (assumptions.salePriceMxn && assumptions.salePriceMxn > 0 ? salePriceMxn : undefined),
      daysAhead: assumptions.daysAhead,
      direction: assumptions.direction ?? 'import',
      amountUsd: assumptions.amountUsd,
      driftPct: [...assumptions.driftPct],
      markupPct,
    },
    derived: {
      baseCostMxn: base.amountMxn,
      exposedRate: exposed.rate,
      exposedCostMxn: exposed.amountMxn,
      costDeltaMxn: exposed.deltaMxn,
      costDeltaPct: exposed.deltaPct,
      comparisonRate: quoteBRate,
      comparisonCostMxn: quoteBCostMxn,
      quoteDifferenceMxn,
      quoteDifferencePct,
      salePriceMxn,
      baseGrossProfitMxn,
      exposedGrossProfitMxn,
      baseGrossMarginPct,
      exposedGrossMarginPct,
      accumulatedImpactMxn,
    },
    facts: allFacts
      .filter((fact) => allowed.has(fact.key) && !(dropForwardMargin && marginKeys.has(fact.key)))
      .map((fact) => {
        const forwardLabel =
          scenarioId === 'forward_protection'
            ? forwardFactLabels(isExport ? 'export' : 'import')[fact.key]
            : undefined;
        return forwardLabel ? { ...fact, label: forwardLabel } : fact;
      }),
    createdAt: now.toISOString(),
  };
}

/**
 * Selecciona hechos para un beat sin decidir su composición.
 *
 * `beatRole` permite que la solución/cierre de un forward renombre la base a "forward
 * pactado / costo final": el mismo número que en el problema era "lo presupuestado", en la
 * resolución es "lo que quedó definido". El resto de los beats conservan las etiquetas del
 * escenario.
 */
export function projectCarouselEconomicFacts(
  scenario: CarouselEconomicScenario,
  factKeys: readonly CarouselEconomicFactKey[],
  beatRole?: string,
): CarouselEconomicFact[] {
  const requested = new Set(factKeys);
  const isForwardResolution =
    scenario.scenarioId === 'forward_protection' &&
    (beatRole === 'solution' || beatRole === 'cta');
  const resolutionLabels = forwardResolutionLabels(scenario.assumptions.direction ?? 'import');
  return scenario.facts
    .filter((fact) => requested.has(fact.key))
    .map((fact) =>
      isForwardResolution && resolutionLabels[fact.key]
        ? { ...fact, label: resolutionLabels[fact.key]! }
        : fact,
    );
}

// ---------------------------------------------------------------------------
// El motor que consume el Creative Plan
// ---------------------------------------------------------------------------

/**
 * Los documentos que un beat pide, con su acumulado cuando la historia lo necesita.
 *
 * Se devuelven juntos porque son una sola decisión: el acumulado no es una propiedad del
 * slide, es la conclusión de una secuencia de documentos. Separarlos permitiría un slide
 * con acumulado y sin documentos que lo sustenten.
 */
export interface CarouselPlanFigures {
  documents: CarouselFigureDocument[];
  /** La suma de las diferencias. Solo en la historia que trata de eso. */
  accumulatedLabel?: string;
}

/**
 * Piso y techo del margen objetivo.
 *
 * No son cosméticos. Con un margen muy chico, un movimiento del 2% en el costo deja el
 * margen del segundo documento casi en cero o negativo, y una hoja que muestra un margen
 * negativo es una afirmación de pérdida — prohibida en las tres ramas, que exigen el
 * riesgo en condicional. Con uno muy grande el movimiento del costo no se nota en el
 * cuadro y la pieza no demuestra nada.
 */
export const MIN_MARGIN_PCT = 10;
export const MAX_MARGIN_PCT = 200;

/**
 * El precio de venta que la historia de margen da por comprometido.
 *
 * Un precio absoluto (`salePriceMxn`) gana al markup: es el número que el usuario teclea
 * para el forward y no tiene por qué derivarse del costo. Si no lo da, se cae al markup
 * sobre el costo base, que es como lo resuelve la hoja de margen de costos.
 */
function committedSalePrice(a: CarouselFxAssumptions, baseCostMxn: number): number {
  if (a.salePriceMxn !== undefined && a.salePriceMxn > 0) {
    return Math.round(a.salePriceMxn * 100) / 100;
  }
  const declared = a.markupPct ?? a.marginPct ?? DEFAULT_MARKUP_PCT;
  const pct = Math.min(Math.max(declared, MIN_MARGIN_PCT), MAX_MARGIN_PCT);
  return Math.round(baseCostMxn * (1 + pct / 100) * 100) / 100;
}

/**
 * Los documentos de un beat, a partir del escenario que declaró el Creative Plan.
 *
 * Es el reemplazo de `figureScenarioFor(sceneKit, role)`, que asignaba cifras por ROL
 * desde una tabla de la rama y por eso contradecía la historia: en una ruta de margen
 * —que prohíbe explícitamente apilar documentos— el rol `risk` recibía tres compras
 * sucesivas, que son la evidencia de la ruta de acumulación. El slide renderizaba una
 * historia distinta de la que el plan había decidido.
 *
 * Los dos vocabularios tampoco se cruzaban: el plan habla en `CarouselFigureScenarioId`
 * —seis escenarios— y el scene kit en `CarouselFigureScenario`, que tiene dos y los dos
 * fueron escritos para la mecánica de dos momentos del tipo de cambio. Aquí se cierra esa
 * traducción y se escriben los tres que faltaban.
 *
 * Nada de esto lo decide un modelo. El plan declara CUÁL escenario, y toda la aritmética
 * vive aquí, porque la aritmética ES el mensaje: una pieza que muestra un tipo de cambio
 * y un total tiene que satisfacer USD × TC = MXN cuando el lector multiplica.
 */
export function buildPlanFigureDocuments(
  scenarioId: CarouselFigureScenarioId,
  assumptions: CarouselFxAssumptions,
  today: Date = new Date(),
): CarouselPlanFigures {
  if (scenarioId === 'none') return { documents: [] };

  const moments = computeCarouselFx(assumptions);
  if (moments.length === 0) return { documents: [] };

  const first = moments[0];
  const last = moments[moments.length - 1];
  const bare = (label: string) => label.replace(/^(USD|MXN)\s+/, '');

  switch (scenarioId) {
    /*
     * Dos cotizaciones simultáneas de la misma obligación.
     *
     * No lleva fechas: comparar proveedores no es comparar el spot de hoy contra una
     * tasa futura. Ambas tasas son inputs editables y el monto USD permanece idéntico.
     */
    case 'quote_comparison': {
      const quoteARate = toCents(assumptions.baseRate);
      const quoteBRate = toCents(assumptions.comparisonRate ?? last.rate);
      const quoteACost = toCents(quoteARate * assumptions.amountUsd);
      const quoteBCost = toCents(quoteBRate * assumptions.amountUsd);
      const difference = toCents(quoteBCost - quoteACost);
      const document = (
        label: string,
        rate: number,
        cost: number,
        isXending: boolean,
      ): CarouselFigureDocument => ({
        label,
        kind: 'COTIZACIÓN',
        fields: [
          { label: 'TOTAL USD', value: formatAmount(assumptions.amountUsd) },
          {
            label: 'TIPO DE CAMBIO',
            value: formatAmount(rate).replace(/,/g, ''),
            colorRole: isXending ? 'control' : undefined,
          },
          ...(!isXending
            ? [{
                label: 'DIFERENCIA',
                value: `${difference >= 0 ? '+' : ''}MXN ${formatAmount(difference)}`,
              }]
            : []),
        ],
        total: {
          label: 'CONVERSIÓN MXN',
          value: formatAmount(cost),
          colorRole: isXending ? 'control' : undefined,
        },
      });

      return {
        documents: [
          document('XENDING', quoteARate, quoteACost, true),
          document('OTRA COTIZACIÓN', quoteBRate, quoteBCost, false),
        ],
      };
    }

    /*
     * La misma obligación con dos tipos de cambio. HOY contra el día del pago.
     *
     * Reusa la mecánica de dos momentos en vez de reescribirla: es exactamente la misma
     * historia numérica que ya se renderizaba bien, y dos implementaciones de la misma
     * comparación acabarían discrepando en los campos o en las fechas.
     */
    case 'rate_comparison':
      return { documents: buildFigureDocuments('two_moment', moments, today) };

    /* La misma operación varias veces, sin sumarlas: eso es el otro escenario. */
    case 'repeated_operations':
      return { documents: buildFigureDocuments('repeated_purchases', moments, today) };

    /* Las mismas operaciones, y la suma de sus diferencias, que es de lo que trata. */
    case 'accumulated_difference':
      return {
        documents: buildFigureDocuments('repeated_purchases', moments, today),
        accumulatedLabel: accumulatedFxImpact(moments).label || undefined,
      };

    /*
     * Un escenario hipotético entre dos niveles, y SIN FECHAS.
     *
     * La fecha es lo que convierte una hipótesis en un pronóstico. "Si el tipo de cambio
     * pasara de A a B" es la única forma en que una rama puede explicar su mecanismo con
     * un nivel que todavía no existe; poner "27 OCT 2026" junto a ese nivel lo afirma, y
     * afirmar hacia dónde va el tipo de cambio está prohibido en las tres ramas.
     *
     * Por eso el sello dice ESCENARIO y no PAGO, y el `kind` no es una cotización: una
     * cotización con fecha es un documento, y un documento se lee como un hecho.
     */
    case 'rate_range': {
      const shape = (m: CarouselFxMoment, label: string, hypothetical: boolean) => ({
        label,
        kind: 'ESCENARIO',
        fields: [
          { label: 'TOTAL USD', value: bare(m.labels.usd) },
          {
            label: 'TIPO DE CAMBIO',
            value: m.labels.rate,
            colorRole: (hypothetical ? 'risk' : 'control') as CarouselColorRole,
          },
          ...(hypothetical && m.labels.pct
            ? [{ label: 'VARIACIÓN', value: m.labels.pct, colorRole: 'risk' as CarouselColorRole }]
            : []),
        ],
        total: {
          label: 'COSTO MXN',
          value: bare(m.labels.mxn),
          colorRole: (hypothetical ? 'risk' : 'control') as CarouselColorRole,
        },
      });

      return {
        documents: [shape(first, 'ACTUAL', false), shape(last, 'SI PASARA A', true)],
      };
    }

    /*
     * Precio de venta fijo contra costo importado variable. La historia del margen.
     *
     * Es la que no existía, y la que faltaba tenía una razón concreta: el margen necesita
     * un PRECIO DE VENTA, y `CarouselFxAssumptions` no lo tenía. Ahora sale del margen
     * objetivo sobre el costo del momento base.
     *
     * El precio se calcula UNA vez y es idéntico en los dos documentos. Eso no es una
     * simplificación del modelo: es el argumento entero. La historia existe porque el
     * precio ya se publicó y lo único que se mueve después es el costo, así que lo que
     * cede es la distancia entre los dos. Un precio que también se moviera contaría que
     * el importador puede repreciar, que es la historia contraria.
     *
     * El MARGEN va en el total y no entre los campos: en una hoja de margen el renglón de
     * abajo es el margen, igual que en una cotización es el costo.
     */
    case 'margin_sensitivity': {
      const salePrice = committedSalePrice(assumptions, first.amountMxn);

      const shape = (m: CarouselFxMoment, label: string, dayOffset: number, moved: boolean) => {
        const margin = Math.round((salePrice - m.amountMxn) * 100) / 100;
        return {
          label,
          kind: 'HOJA DE MARGEN',
          date: formatFigureDate(shiftDays(today, dayOffset)),
          fields: [
            // Navy: el precio comprometido no es el beneficio ni el riesgo, y es el valor
            // que tiene que leerse IDÉNTICO en los dos documentos.
            { label: 'PRECIO DE VENTA', value: formatAmount(salePrice) },
            {
              label: 'COSTO IMPORTADO',
              value: formatAmount(m.amountMxn),
              colorRole: (moved ? 'risk' : 'control') as CarouselColorRole,
            },
            ...(moved && m.labels.pct
              ? [
                  {
                    label: 'VARIACIÓN DEL COSTO',
                    value: m.labels.pct,
                    colorRole: 'risk' as CarouselColorRole,
                  },
                ]
              : []),
          ],
          total: {
            label: 'MARGEN',
            value: formatAmount(margin),
            colorRole: (moved ? 'risk' : 'control') as CarouselColorRole,
          },
        };
      };

      return {
        documents: [shape(first, 'HOY', 0, false), shape(last, 'PAGO', 60, true)],
      };
    }

    /*
     * El forward: el costo pactado hoy contra el costo si no se cubre y la tasa sube.
     *
     * Dos documentos del MISMO pedido: el pactado (turquesa, cierto) y el expuesto (coral,
     * lo que hubiera costado). El monto USD es idéntico; lo que cambia es la tasa. Sin
     * fecha de calendario: el horizonte va como etiqueta relativa ("60 DÍAS"), porque una
     * fecha convertiría el ejemplo en un pronóstico.
     *
     * El margen es opcional: solo cuando el usuario dio un precio de venta. Con precio, el
     * renglón de margen muestra cuánto cede la utilidad; sin él, la historia es el puro
     * costo. El precio de venta se lee IDÉNTICO en los dos: lo que se mueve es el costo.
     */
    case 'forward_protection': {
      const days = assumptions.daysAhead ?? 60;
      const hasMargin = assumptions.salePriceMxn !== undefined && assumptions.salePriceMxn > 0;
      const fixedMxn = hasMargin ? committedSalePrice(assumptions, first.amountMxn) : 0;
      /*
       * Importas: el MXN variable es el COSTO, y el fijo es tu precio de venta. Exportas:
       * el MXN variable es el INGRESO, y el fijo es tu costo. La utilidad y el margen se
       * invierten en consecuencia; el margen siempre se mide sobre el ingreso.
       */
      const isExport = (assumptions.direction ?? 'import') === 'export';
      const fixedLabel = isExport ? 'COSTO FIJO' : 'PRECIO DE VENTA';
      const variableLabel = isExport ? 'INGRESO MXN' : 'COSTO MXN';

      const shape = (
        m: CarouselFxMoment,
        label: string,
        kind: string,
        exposed: boolean,
      ): CarouselFigureDocument => {
        const role = (exposed ? 'risk' : 'control') as CarouselColorRole;
        const fields: CarouselFigureField[] = [
          { label: 'TIPO DE CAMBIO', value: m.labels.rate, colorRole: role },
        ];
        if (exposed && m.labels.pct) {
          fields.push({ label: 'VARIACIÓN', value: m.labels.pct, colorRole: 'risk' });
        }
        if (hasMargin) {
          // El valor fijo es el mismo en los dos: eso hace legible que lo que cambia es el
          // otro lado. La utilidad y el margen se mueven, y ahí se ve el efecto.
          fields.push({ label: fixedLabel, value: formatAmount(fixedMxn) });
          const profit = Math.round((isExport ? m.amountMxn - fixedMxn : fixedMxn - m.amountMxn) * 100) / 100;
          const revenue = isExport ? m.amountMxn : fixedMxn;
          const marginPct = revenue > 0 ? Math.round((profit / revenue) * 1000) / 10 : 0;
          fields.push({ label: 'UTILIDAD BRUTA', value: formatAmount(profit), colorRole: role });
          fields.push({ label: 'MARGEN BRUTO', value: `${marginPct.toFixed(1)}%`, colorRole: role });
        } else {
          // Sin margen: la historia es el puro movimiento. USD como ancla de la operación.
          fields.unshift({ label: 'TOTAL USD', value: bare(m.labels.usd) });
        }
        return {
          label,
          kind,
          fields,
          total: { label: variableLabel, value: bare(m.labels.mxn), colorRole: role },
        };
      };

      /*
       * Dos momentos de la MISMA operación: al presupuestar (hoy) y al pago sin cobertura
       * a N días. No es "forward pactado vs no": este slide muestra el RIESGO, el forward
       * lo resuelve el slide siguiente. El escenario a N días se rotula como ilustrativo,
       * que es la única forma en que la rama puede mostrar una tasa que todavía no existe.
       */
      return {
        documents: [
          shape(first, 'HOY', 'AL PRESUPUESTAR', false),
          shape(last, 'SIN COBERTURA', `ESCENARIO ILUSTRATIVO · ${days} DÍAS`, true),
        ],
      };
    }

    /*
     * Un solo valor ya definido, sin contraparte.
     *
     * Un documento y nada más, y ahí está su significado: el resto de los escenarios
     * enfrentan dos estados porque su historia es el movimiento. Esta historia es que no
     * hay movimiento, así que una segunda tarjeta la contradiría — habría dos valores que
     * comparar donde el argumento es que solo hay uno.
     *
     * Todo en turquesa o navy, ningún coral: no hay exposición que señalar.
     */
    case 'cashflow_certainty':
      return {
        documents: [
          {
            label: 'COSTO DEFINIDO',
            kind: 'COTIZACIÓN',
            date: formatFigureDate(today),
            fields: [
              { label: 'TOTAL USD', value: bare(first.labels.usd) },
              { label: 'TIPO DE CAMBIO', value: first.labels.rate, colorRole: 'control' },
            ],
            total: {
              label: 'COSTO MXN',
              value: bare(first.labels.mxn),
              colorRole: 'control',
            },
          },
        ],
      };

    /*
     * Un escenario que el plan puede declarar y este motor no sabe construir.
     *
     * Sin documentos, a propósito. Inventarle una forma parecida es cómo se llegó al
     * fallo que este archivo viene a arreglar: un slide con los documentos de otra
     * historia se ve perfectamente bien y cuenta algo que nadie decidió. Un slide sin
     * cifras se nota y se puede corregir.
     */
    default:
      return { documents: [] };
  }
}

/**
 * Brand elements the slide at `index` carries under a preset.
 *
 * Addressed by index, not by role, because a role can repeat: a checklist is three
 * `signal` slides and a timeline is three `moment` slides. Asking "does this role
 * carry the logo" put it on all three, which is three lockups in one set.
 *
 * When the placement names a repeated role, the FIRST slide of that role owns the
 * element — it is the cover, the one that shows up in the feed.
 */
export function brandElementsForSlide(
  preset: CarouselPreset,
  index: number,
): CarouselBrandElement[] {
  const role = preset.roles[index];
  if (!role || preset.roles.indexOf(role) !== index) return [];

  return (Object.entries(preset.brandPlacement) as Array<
    [CarouselBrandElement, CarouselSlideRole]
  >)
    .filter(([, target]) => target === role)
    .map(([element]) => element);
}

/**
 * Design-Studio-specific payload stored inside `generated_ideas.piece_v2`
 * (JSONB). Using the existing column avoids a schema migration while marking
 * the row's origin (`source`) so the pipeline's IdeasPanel can filter it out.
 * The multichannel render only reads piece_v2 when it has `overlays`+`captions`,
 * so this shape is never misinterpreted there.
 */
export interface DesignStudioIdeaMeta {
  source: 'design_studio';
  angleName?: string | null;
  industryName?: string | null;
  imageMode: CopyBankImageMode;
  imageType?: DesignImageType;   // active type for single mode
  imagePrompt?: string;          // generated prompt for single mode
  imagePromptRevision?: string;  // invalidates cached prompts after runtime/style changes
  masterImagePromptVersion?: MasterImagePromptVersion; // exact V1/V2 snapshot used
  imageBackgroundStyle?: 'navy' | 'light_cream' | 'white' | 'white_2';
  corridorOverride?: CorridorOverride;
  corridorAnalysis?: CorridorAnalysis;
  /** Carousel derived from this copy (Stage C). One per bank row. */
  carousel?: CarouselMeta;
  // Feedback loop: 'liked' copies steer new batches (imitate tone), 'disliked'
  // ones are avoided. A user-corrected+saved copy is auto-marked 'liked'.
  rating?: 'liked' | 'disliked';
}

/** Marker string kept in one place so producers and filters never drift. */
export const DESIGN_STUDIO_SOURCE = 'design_studio' as const;

/** True when a generated_ideas row originated in the Design Studio copy bank. */
export function isDesignStudioIdea(pieceV2: unknown): boolean {
  return !!pieceV2 && typeof pieceV2 === 'object'
    && (pieceV2 as { source?: string }).source === DESIGN_STUDIO_SOURCE;
}

// --- Visual Selections (Mode A) ---

export interface VisualSelections {
  background: string | null;    // white-classic | white-xending-v2 | white-2 | dark-navy | legacy/custom
  visualStyle: string | null;   // 'minimalist' | 'glassmorphism' | 'bold' | 'financial' | 'gradients' | 'hero-photo' | custom
  contentType: string | null;   // 'stat' | 'news' | 'educational' | 'promo' | 'comparison' | 'event' | 'testimonial' | custom
  heroElement: string | null;   // 'big-number' | 'main-photo' | 'icon' | 'floating-badge' | 'no-image' | custom
  platform: PlatformFormat | null;
  // Content context
  contentMode: ContentMode;
  commercialBranchSlug: string | null;  // only when contentMode === 'branch'
  customIdea: string | null;            // only when contentMode === 'custom'
  // Narrative angle (only when contentMode === 'branch'). Drives copy variety
  // and enables persistence to content_library for cross-session de-duplication.
  // Mirrors the dimensions used by the Generador Combinable flow.
  narrativeAngleId: string | null;
  narrativeAngleSlug: string | null;
  narrativeAngleName: string | null;
  funnelStage: string | null;
  narrativePromptInstruction: string | null;
  // Industry/vertical dimension. Adds per-industry relevance + variety.
  // industryAuto = cycle through all verticals per generation (max variety).
  industryVerticalId: string | null;
  industryVerticalName: string | null;
  industryAuto: boolean;
  // Piece-level copy and image prompt (optional, for full-package mode)
  pieceCopy: PieceCopy | null;
  pieceImagePrompt: PieceImagePrompt | null;
  // Optional route hints for mapa_rutas. Auto mode infers from copy/context.
  corridorOverride?: CorridorOverride;
  // When true, the AI bakes the exact headline/CTA into the generated image.
  // When false (default), the image stays text-free and the template overlays copy.
  textInImage: boolean;
}

/** Full narrative angle payload returned by AngleSelector. */
export interface NarrativeAngleSelection {
  id: string;
  slug: string;
  name: string;
  funnelStage: string;
  promptInstruction: string;
}

/** Industry selection: a specific vertical, 'auto' (cycle) or null (none). */
export type IndustrySelection = { id: string; name: string } | 'auto' | null;

export type SelectionCategory = 'background' | 'visualStyle' | 'contentType' | 'heroElement' | 'platform';

export interface SelectionOption {
  value: string;
  label: string;
  icon?: string;        // Lucide icon name
  description?: string;
}

export interface CategoryConfig {
  id: SelectionCategory;
  label: string;
  options: SelectionOption[];
  allowCustom: boolean;
}

// --- Brand Palette ---

export interface BrandPalette {
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  fonts: {
    display?: string;
    body?: string;
    mono?: string;
  };
  logo_url: string;
  disclaimer?: string;
}

// --- Generated Mockups ---

export interface GeneratedMockup {
  index: number;
  image_base64: string;
  prompt_used: string;
}

// --- HTML Iteration ---

export interface HtmlIteration {
  version: number;
  html: string;
  feedback: string | null;  // null for the first version
  created_at: string;
}

// --- Design Session ---

export type DesignSessionStatus = 'active' | 'completed' | 'discarded';

export interface DesignSession {
  id: string;
  business_id: string;
  status: DesignSessionStatus;
  input_mode: 'visual' | 'reference';
  selections: VisualSelections | null;
  reference_image_url: string | null;
  reference_description: string | null;
  platform: PlatformFormat | null;
  mockups: GeneratedMockup[];
  selected_mockup_index: number | null;
  current_html: string | null;
  html_history: HtmlIteration[];
  iteration_count: number;
  created_at: string;
  updated_at: string;
}

// --- Template Converter ---

export interface TemplateSlot {
  name: string;           // 'headline' | 'subcopy' | 'cta' | 'imageUrl' | 'disclaimer'
  type: 'text' | 'image';
  required: boolean;
}

export interface TemplateConverterInput {
  html: string;
  brand_palette: BrandPalette;
}

export interface TemplateConverterOutput {
  template_html: string;          // HTML with {{placeholders}}
  detected_slots: TemplateSlot[]; // Detected slots
}

// --- API Request/Response Types ---

// --- Branch Content Ingredients ---

/**
 * Pre-approved content ingredients for a commercial branch + angle combination.
 * These are injected into the image generation prompt as available content
 * that GPT can use creatively (not prescriptive layout).
 */
export interface BranchContentIngredients {
  headlines: string[];
  sublines: string[];
  ctas: string[];
  benefit_phrases?: string[];
  data_sets?: Record<string, string>[];
  big_stats?: string[];
  photo_direction: string;
  // Strategic context that differentiates this branch from others
  branch_context?: {
    name: string;
    objetivo?: string;
    dolor?: string;
    promesa?: string;
  };
}

export interface GenerateMockupsRequest {
  business_id: string;
  brand_palette: BrandPalette;
  mode: 'visual' | 'reference';
  // Mode A
  selections?: VisualSelections;
  // Mode B
  reference_image_base64?: string;
  reference_description?: string;
  // Content context (new)
  content_mode?: ContentMode;
  branch_ingredients?: BranchContentIngredients;
  custom_idea?: string;
  // Piece-level copy and image prompt
  piece_copy?: PieceCopy;
  piece_image_prompt?: PieceImagePrompt;
  // Iteration feedback — regenerate with user corrections
  iteration_feedback?: string;
  previous_prompt?: string;
  // Common
  platform: PlatformFormat;
  count: 3;
}

export interface GenerateMockupsResponse {
  mockups: GeneratedMockup[];
}

export interface DesignHtmlFromMockupRequest {
  business_id: string;
  brand_palette: BrandPalette;
  mockup_image_base64: string;
  platform: PlatformFormat;
  // For iterations
  current_html?: string;
  iteration_feedback?: string;
}

export interface DesignHtmlResponse {
  html: string;
}

export interface SaveTemplateRequest {
  name: string;
  business_id: string;
  template_html: string;
  platform: PlatformFormat;
  slots: TemplateSlot[];
  source_mockup_url?: string;
  thumbnail_base64?: string;
}

export interface SaveTemplateResponse {
  id: string;
  name: string;
  created_at: string;
}

// --- Zustand Store Types ---

export interface DesignStudioState {
  // Session
  sessionId: string | null;
  sessionStatus: DesignSessionStatus;

  // Brand Palette (loaded automatically)
  brandPalette: BrandPalette | null;

  // Input mode
  inputMode: 'visual' | 'reference';

  // Mode A: Visual selections
  selections: VisualSelections;

  // Mode B: Reference image
  referenceImage: File | null;
  referenceImagePreview: string | null;
  referenceDescription: string;

  // Platform
  selectedPlatform: PlatformFormat | null;

  // Generated mockups
  mockups: GeneratedMockup[];
  selectedMockupIndex: number | null;

  // Copy bank: which candidate (generated_ideas row id) is currently active.
  // The active candidate's copy is mirrored into selections.pieceCopy so the
  // Stage-B visual editor and mockup generation consume it unchanged.
  activeCandidateId: string | null;

  // HTML
  currentHtml: string | null;
  htmlHistory: HtmlIteration[];
  iterationCount: number;

  // Loading states
  isGeneratingMockups: boolean;
  isGeneratingHtml: boolean;
  isSaving: boolean;
  error: string | null;
}

export interface DesignStudioActions {
  // Session
  initSession(): void;
  restoreSession(session: DesignSession): void;
  discardSession(): void;
  markSessionCompleted(): void;

  // Selections
  setInputMode(mode: 'visual' | 'reference'): void;
  setSelection(category: SelectionCategory, value: string): void;
  setCustomValue(category: SelectionCategory, value: string): void;
  setPlatform(platform: PlatformFormat): void;

  // Content mode
  setContentMode(mode: ContentMode): void;
  setCommercialBranch(slug: string | null): void;
  setCustomIdea(idea: string): void;
  setNarrativeAngle(angle: NarrativeAngleSelection | null): void;
  setIndustryVertical(industry: IndustrySelection): void;

  // Piece copy & image prompt
  setPieceCopy(copy: PieceCopy | null): void;
  updatePieceCopyField(field: keyof PieceCopy, value: string): void;
  setPieceImagePrompt(prompt: PieceImagePrompt | null): void;
  setPieceImageType(type: DesignImageType): void;
  setPieceImagePromptText(text: string): void;
  setCorridorOverride(corridor: CorridorOverride): void;
  setTextInImage(value: boolean): void;

  // Reference
  setReferenceImage(file: File | null): void;
  setReferenceDescription(desc: string): void;

  // Mockups
  setMockups(mockups: GeneratedMockup[]): void;
  selectMockup(index: number): void;
  invalidateGeneratedVisuals(): void;

  // Copy bank
  setActiveCandidate(id: string | null, copy: PieceCopy | null): void;

  // HTML
  setCurrentHtml(html: string): void;
  addIteration(html: string, feedback: string): void;

  // Loading
  setGeneratingMockups(loading: boolean): void;
  setGeneratingHtml(loading: boolean): void;
  setSaving(loading: boolean): void;
  setError(error: string | null): void;

  // Reset
  reset(): void;
}

export type DesignStudioStore = DesignStudioState & DesignStudioActions;
