-- ---------------------------------------------------------------------------
-- Seed: banco vertical de coberturas / forwards — importadores (69 copys)
-- ---------------------------------------------------------------------------
-- GENERADO por scripts/build-copy-bank-v31.mjs --emit. No editar a mano;
-- cambia docs/prompts/copy-banks/coberturas.importadores.vertical.v2.md y re-genera.
--
-- Corre DESPUÉS de seed_20260820_copy_bank_v31.sql (que borra e inserta el banco
-- maestro): agrega los verticales sin tocar ese seed.
--
-- Idempotente: el índice único (business, branch, corridor, lower(headline))
-- para status in ('approved','seed') hace que un re-run no duplique.
-- ---------------------------------------------------------------------------

insert into public.copy_bank_items (
  business_id, branch_slug, corridor, industry,
  headline, subcopy, cta, cta_alt,
  angle_tag, angle_label, formula, tone_bucket,
  needs_legal_note, legal_note,
  status, source, prompt_revision, kit_version, business_side
)
select
  b.id,
  v.branch_slug, v.corridor, v.industry,
  v.headline, v.subcopy, v.cta, v.cta_alt,
  v.angle_tag, v.angle_label, v.formula, v.tone_bucket,
  v.needs_legal_note, v.legal_note,
  v.status, v.source, v.prompt_revision, v.kit_version, v.business_side
from (values
  ('coberturas', 'industria', 'autopartes', 'El lote de rodamientos se paga dentro de 60 días', 'El costo en pesos todavía puede cambiar antes del vencimiento.', 'Planea hoy tus costos futuros', '{}'::text[], 'pago_futuro_60_dias', 'pago futuro 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'autopartes', 'Ya vendiste las balatas. La reposición sigue cotizada en dólares', 'El tipo de cambio puede modificar el margen del siguiente lote.', 'Protege tu margen', '{}'::text[], 'reposicion_margen_comprometido', 'reposición / margen comprometido', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'autopartes', 'Cada mes compras arneses. Cada pago llega en una fecha distinta', 'Una cobertura puede ayudarte a dar mayor estabilidad al costo de tus compras recurrentes.', 'Administra tu riesgo cambiario', '{}'::text[], 'compras_recurrentes', 'compras recurrentes', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'autopartes', 'El lote de baterías llega en 90 días. El presupuesto ya está definido', 'El tipo de cambio todavía puede modificar cuánto terminarás pagando en pesos.', 'Protege tus costos', '{}'::text[], 'presupuesto_90_dias', 'presupuesto + 90 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'autopartes', 'El módulo electrónico lleva anticipo hoy y saldo antes del embarque', 'Dos fechas de pago pueden significar dos momentos de riesgo cambiario.', 'Planea tus costos', '{}'::text[], 'anticipo_saldo', 'anticipo + saldo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'autopartes', 'Los discos de freno ya tienen precio con tu cliente. El costo de reposición no', 'Una cobertura puede ayudarte a proteger el margen del siguiente pedido.', 'Cuida tu margen', '{}'::text[], 'precio_de_venta_fijo_reposicion_variable', 'precio de venta fijo / reposición variable', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'autopartes', 'Cotizaste las suspensiones para ganar el programa. El dólar puede cambiar la ecuación', 'Una cobertura puede ayudarte a proteger el margen con el que competiste.', 'Protege tu margen', '{}'::text[], 'competitividad', 'competitividad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'autopartes', 'La transmisión tiene precio de venta. Su costo final en pesos todavía no', 'Una cobertura puede reducir la incertidumbre antes de pagar al proveedor.', 'Define tu costo cambiario', '{}'::text[], 'precio_de_venta_costo_futuro', 'precio de venta / costo futuro', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'autopartes', 'El pedido de sensores está confirmado. El pago será en 60 días', 'Un forward puede ayudarte a definir hoy el tipo de cambio de ese pago.', 'Define hoy. Paga después.', '{}'::text[], 'pedido_confirmado_60_dias', 'pedido confirmado + 60 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'La CNC que compras hoy se liquida dentro de 90 días', 'Una cobertura puede ayudarte a dar mayor certidumbre al costo en pesos.', 'Protege tus costos', '{}'::text[], 'pago_futuro_90_dias', 'pago futuro 90 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'La inyectora lleva anticipo hoy. El saldo se paga después', 'El tipo de cambio puede ser diferente en cada fecha de pago.', 'Planea tus costos', '{}'::text[], 'anticipo_saldo', 'anticipo + saldo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'El molde se paga antes de fabricar la primera pieza', 'El tipo de cambio también forma parte de esa inversión inicial.', 'Define tu costo cambiario', '{}'::text[], 'inversion_previa_a_produccion', 'inversión previa a producción', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'La prensa estará lista después del FAT. El presupuesto ya está aprobado', 'Una cobertura puede ayudarte a cuidar el costo hasta el pago final.', 'Planea hoy tus costos futuros', '{}'::text[], 'fabricacion_presupuesto_aprobado', 'fabricación + presupuesto aprobado', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'El compresor ya está fabricándose. El saldo se paga antes del embarque', 'Un forward puede ayudarte a definir el tipo de cambio de ese saldo.', 'Cotiza un forward', '{}'::text[], 'fabricacion_saldo_futuro', 'fabricación + saldo futuro', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'El torno está cotizado en euros. Tu CAPEX está aprobado en pesos', 'Una cobertura puede ayudarte a cuidar el presupuesto de la inversión.', 'Protege tus costos', '{}'::text[], 'eur_vs_capex_mxn', 'EUR vs. CAPEX MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'Una línea de producción puede tener varios pagos antes de arrancar', 'Cada desembolso puede tener un tipo de cambio diferente.', 'Administra tu riesgo cambiario', '{}'::text[], 'varios_desembolsos', 'varios desembolsos', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'Vendiste la instalación. Todavía falta comprar la bomba industrial', 'El tipo de cambio puede modificar el margen del proyecto antes de la compra.', 'Protege tu margen', '{}'::text[], 'proyecto_vendido_compra_posterior', 'proyecto vendido + compra posterior', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'Cotizaste la máquina para ganar el proyecto. El saldo se paga en 90 días', 'Una cobertura puede ayudarte a proteger el margen con el que competiste.', 'Protege tu margen', '{}'::text[], 'competitividad_pago_90_dias', 'competitividad + pago 90 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'maquinaria', 'El saldo de la inyectora ya tiene monto y fecha', 'Un forward puede ayudarte a definir hoy el tipo de cambio aplicable.', 'Define hoy. Paga después.', '{}'::text[], 'monto_fecha_conocidos', 'monto + fecha conocidos', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'electronicos', 'Las tarjetas PCB se pagan en 60 días. La producción ya está programada', 'El costo en pesos todavía puede cambiar antes del vencimiento.', 'Protege tus costos', '{}'::text[], 'produccion_60_dias', 'producción + 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'electronicos', 'Las cámaras ya tienen precio de venta. Falta reponer el inventario', 'El tipo de cambio puede modificar el margen del siguiente pedido.', 'Cuida tu margen', '{}'::text[], 'precio_de_venta_reposicion', 'precio de venta + reposición', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'electronicos', 'Miles de chips hacen relevante una variación pequeña', 'El volumen también amplifica el efecto sobre el costo total.', 'Protege tus costos', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'electronicos', 'El pedido de baterías es para la próxima temporada', 'El costo final en pesos todavía puede cambiar antes del pago.', 'Planea hoy tus costos futuros', '{}'::text[], 'temporada_futura', 'temporada futura', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'electronicos', 'Los cargadores se venden en pesos. El proveedor cobra en dólares', 'Una cobertura puede ayudarte a cuidar el margen de la reposición.', 'Protege tu margen', '{}'::text[], 'venta_mxn_compra_usd', 'venta MXN / compra USD', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'electronicos', 'Dos lotes de displays. Dos fechas diferentes de pago', 'Cada compra puede terminar con un costo distinto en pesos.', 'Administra tu riesgo cambiario', '{}'::text[], 'dos_lotes_dos_fechas', 'dos lotes / dos fechas', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'electronicos', 'Cotizaste los sensores para mantenerte competitivo', 'El tipo de cambio puede apretar el margen antes de reponer el inventario.', 'Protege tu margen', '{}'::text[], 'competitividad_reposicion', 'competitividad / reposición', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'electronicos', 'El inventario de fuentes de poder llega antes de temporada alta', 'Una cobertura puede ayudarte a dar mayor certidumbre al costo de la reposición.', 'Da certidumbre a tus costos', '{}'::text[], 'inventario_para_temporada', 'inventario para temporada', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'electronicos', 'Las pantallas ya están pedidas. El pago será dentro de 60 días', 'Un forward puede ayudarte a definir hoy el tipo de cambio.', 'Cotiza un forward', '{}'::text[], 'pedido_confirmado_60_dias', 'pedido confirmado + 60 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'textiles_calzado', 'El algodón se compra hoy. La colección se vende meses después', 'Una cobertura puede ayudarte a dar mayor certidumbre al costo desde la compra.', 'Planea hoy tus costos futuros', '{}'::text[], 'materia_prima_temporada_futura', 'materia prima + temporada futura', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'textiles_calzado', 'El cuero se paga en dólares. El zapato se vende en pesos', 'El tipo de cambio puede modificar el margen por par.', 'Protege tu margen', '{}'::text[], 'compra_usd_venta_mxn', 'compra USD / venta MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'textiles_calzado', 'Ya definiste el precio de temporada. Falta pagar la producción', 'El costo en pesos todavía puede cambiar antes del embarque.', 'Cuida tu margen', '{}'::text[], 'precio_definido_pago_futuro', 'precio definido + pago futuro', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'textiles_calzado', 'Miles de metros de tela hacen relevante cualquier movimiento cambiario', 'El volumen puede amplificar el efecto sobre el costo del pedido.', 'Protege tus costos', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'textiles_calzado', 'Cotizaste la colección para competir en temporada', 'El tipo de cambio puede modificar el margen con el que ganaste la venta.', 'Protege tu margen', '{}'::text[], 'competitividad_temporada', 'competitividad / temporada', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'textiles_calzado', 'La fábrica de calzado recibió el anticipo. El saldo viene después', 'Dos fechas de pago pueden requerir dos decisiones cambiarias.', 'Planea tus costos', '{}'::text[], 'anticipo_saldo', 'anticipo + saldo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'textiles_calzado', 'La producción de chamarras termina en 60 días. El saldo ya tiene fecha', 'Un forward puede ayudarte a definir hoy el tipo de cambio del pago.', 'Define hoy. Paga después.', '{}'::text[], 'produccion_saldo_60_dias', 'producción + saldo 60 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'solar_iluminacion_electrico', 'Los paneles se compran hoy. Los inversores, semanas después', 'Dos compras pueden significar dos momentos de riesgo cambiario.', 'Planea tus costos', '{}'::text[], 'compras_en_fechas_distintas', 'compras en fechas distintas', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'solar_iluminacion_electrico', 'El proyecto dura 90 días. El presupuesto ya está cerrado', 'El tipo de cambio todavía puede mover el costo durante la ejecución.', 'Protege tus costos', '{}'::text[], 'presupuesto_cerrado_90_dias', 'presupuesto cerrado + 90 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'solar_iluminacion_electrico', 'El cliente ya aprobó el proyecto. Falta comprar las baterías', 'Una cobertura puede ayudarte a cuidar el margen de la instalación.', 'Protege tu margen', '{}'::text[], 'proyecto_aprobado_compra_futura', 'proyecto aprobado + compra futura', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'solar_iluminacion_electrico', 'El transformador tiene entrega futura. Su costo está en dólares', 'Una cobertura puede dar mayor certidumbre antes del pago.', 'Planea hoy tus costos futuros', '{}'::text[], 'entrega_futura', 'entrega futura', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'solar_iluminacion_electrico', 'Cable, breakers y tableros se compran en etapas distintas', 'Cada desembolso puede tener un tipo de cambio diferente.', 'Administra tu riesgo cambiario', '{}'::text[], 'compras_por_etapas', 'compras por etapas', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'solar_iluminacion_electrico', 'Cotizaste los paneles para ganar el proyecto', 'El tipo de cambio puede cambiar el margen con el que competiste.', 'Protege tu margen', '{}'::text[], 'competitividad', 'competitividad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'solar_iluminacion_electrico', 'El pedido de inversores está confirmado para pagar en 60 días', 'Un forward puede ayudarte a definir hoy el tipo de cambio.', 'Cotiza un forward', '{}'::text[], 'pedido_confirmado_60_dias', 'pedido confirmado + 60 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'solar_iluminacion_electrico', 'El transformador llega en tres meses. El pago ya está programado', 'Un forward puede ayudarte a definir el tipo de cambio antes del vencimiento.', 'Define hoy. Paga después.', '{}'::text[], 'entrega_90_dias', 'entrega 90 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'hvac_climatizacion', 'El chiller se compra meses después de adjudicar el proyecto', 'El tipo de cambio todavía puede modificar el presupuesto de la obra.', 'Protege tus costos', '{}'::text[], 'adjudicacion_compra_futura', 'adjudicación + compra futura', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'hvac_climatizacion', 'El elevador lleva anticipo hoy y saldo antes de la entrega', 'Dos fechas de pago pueden implicar dos momentos cambiarios diferentes.', 'Planea tus costos', '{}'::text[], 'anticipo_saldo', 'anticipo + saldo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'hvac_climatizacion', 'Ya vendiste la obra. Falta comprar las manejadoras de aire', 'El tipo de cambio todavía puede modificar el margen del proyecto.', 'Protege tu margen', '{}'::text[], 'obra_vendida_compra_futura', 'obra vendida + compra futura', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'hvac_climatizacion', 'El compresor llega en 60 días. El presupuesto ya está aprobado', 'Una cobertura puede darte mayor certidumbre antes del pago.', 'Planea hoy tus costos futuros', '{}'::text[], 'presupuesto_60_dias', 'presupuesto + 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'hvac_climatizacion', 'Bombas, chillers y controles se compran en etapas distintas', 'Cada compra puede llegar con un costo diferente en pesos.', 'Administra tu riesgo cambiario', '{}'::text[], 'obra_por_etapas', 'obra por etapas', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'hvac_climatizacion', 'El contrato del cliente ya tiene precio. La refrigeración todavía falta por comprar', 'Una cobertura puede ayudarte a proteger el margen del proyecto.', 'Protege tu margen', '{}'::text[], 'contrato_fijo_compra_pendiente', 'contrato fijo + compra pendiente', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'hvac_climatizacion', 'Cotizaste el sistema VRF para ganar la obra', 'El tipo de cambio puede cambiar el margen con el que competiste.', 'Protege tu margen', '{}'::text[], 'competitividad', 'competitividad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'hvac_climatizacion', 'El chiller ya está en fabricación. El saldo se paga antes del embarque', 'Un forward puede ayudarte a definir hoy el tipo de cambio del saldo.', 'Cotiza un forward', '{}'::text[], 'fabricacion_saldo_futuro', 'fabricación + saldo futuro', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'hvac_climatizacion', 'El elevador ya tiene fecha de entrega y pago', 'Un forward puede ayudarte a definir también el tipo de cambio.', 'Define hoy. Paga después.', '{}'::text[], 'fecha_pago_conocidos', 'fecha + pago conocidos', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'empaques_envases', 'El margen de cada botella también depende del costo de la resina', 'Una cobertura puede ayudarte a cuidar el costo de producción.', 'Protege tu margen', '{}'::text[], 'margen_por_unidad', 'margen por unidad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'empaques_envases', 'Millones de tapas hacen grande una diferencia pequeña', 'El volumen puede amplificar el efecto sobre el costo del lote.', 'Protege tus costos', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'empaques_envases', 'La resina entra a producción el próximo mes. El pago sigue en dólares', 'El costo en pesos todavía puede cambiar antes de recibirla.', 'Planea tus costos', '{}'::text[], 'produccion_futura', 'producción futura', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'empaques_envases', 'Cada mes vuelves a comprar pellets para mantener la producción', 'Cada compra llega con una nueva fecha y un nuevo riesgo cambiario.', 'Administra tu riesgo cambiario', '{}'::text[], 'compra_recurrente', 'compra recurrente', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'empaques_envases', 'El precio de las cajas ya está pactado con tu cliente', 'El costo del material importado todavía puede cambiar.', 'Protege tu margen', '{}'::text[], 'precio_de_venta_fijo', 'precio de venta fijo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'empaques_envases', 'Cotizaste los envases para ganar el contrato', 'El tipo de cambio puede apretar el margen con el que competiste.', 'Protege tu margen', '{}'::text[], 'competitividad', 'competitividad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'empaques_envases', 'El molde de las botellas se paga antes de producir la primera unidad', 'Una cobertura puede dar mayor certidumbre a esa inversión.', 'Protege tus costos', '{}'::text[], 'inversion_previa_a_produccion', 'inversión previa a producción', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'empaques_envases', 'El pedido de película plástica se paga dentro de 60 días', 'El costo futuro en pesos todavía puede cambiar.', 'Planea hoy tus costos futuros', '{}'::text[], 'pago_futuro_60_dias', 'pago futuro 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'empaques_envases', 'La compra de resina ya está programada para dentro de 90 días', 'Un forward puede ayudarte a definir hoy el tipo de cambio del pago.', 'Define hoy. Paga después.', '{}'::text[], 'compra_programada_90_dias', 'compra programada 90 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'insumos_industriales', 'Ya vendiste las válvulas. El siguiente pedido sigue en dólares', 'Una cobertura puede ayudarte a cuidar el margen de la reposición.', 'Protege tu margen', '{}'::text[], 'reposicion', 'reposición', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'insumos_industriales', 'El pallet de herramientas llega después. Su costo en pesos todavía puede cambiar', 'Una cobertura puede ayudarte a definir mejor el costo del siguiente pago.', 'Define tu costo cambiario', '{}'::text[], 'entrega_futura', 'entrega futura', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'insumos_industriales', 'Cada mes repones mangueras y conexiones del inventario', 'Cada compra vuelve a tener una fecha y un tipo de cambio distintos.', 'Administra tu riesgo cambiario', '{}'::text[], 'reposicion_mensual', 'reposición mensual', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'insumos_industriales', 'Los abrasivos ya tienen precio de catálogo. La reposición todavía no', 'El tipo de cambio puede modificar el margen del siguiente lote.', 'Cuida tu margen', '{}'::text[], 'catalogo_fijo_reposicion', 'catálogo fijo + reposición', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'insumos_industriales', 'Cientos de cajas de tornillería cambian la escala del riesgo', 'Una cobertura puede darte mayor certidumbre sobre el costo total.', 'Protege tus costos', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'insumos_industriales', 'La bomba industrial tiene precio. El proyecto ya tiene presupuesto', 'El tipo de cambio todavía puede modificar el costo antes de comprarla.', 'Protege tu margen', '{}'::text[], 'proyecto_presupuestado', 'proyecto presupuestado', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'insumos_industriales', 'Cotizaste las herramientas de corte para ganar el contrato', 'El tipo de cambio puede modificar el margen antes de reponerlas.', 'Protege tu margen', '{}'::text[], 'competitividad', 'competitividad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador'),
  ('coberturas', 'industria', 'insumos_industriales', 'El compresor se paga antes del embarque. La fecha ya está definida', 'Un forward puede ayudarte a definir hoy el tipo de cambio de ese saldo.', 'Cotiza un forward', '{}'::text[], 'pago_antes_de_embarque', 'pago antes de embarque', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'importador')
) as v(
  branch_slug, corridor, industry,
  headline, subcopy, cta, cta_alt,
  angle_tag, angle_label, formula, tone_bucket,
  needs_legal_note, legal_note,
  status, source, prompt_revision, kit_version, business_side
)
cross join (select id from public.business_tenants where slug = 'xending') b
on conflict do nothing;

-- Verificación
select branch_slug, corridor, count(*) as n
from public.copy_bank_items
where status = 'seed'
group by 1, 2
order by 1, 2;
