-- ---------------------------------------------------------------------------
-- Seed: banco vertical de coberturas / forwards — exportadores (80 copys)
-- ---------------------------------------------------------------------------
-- GENERADO por scripts/build-copy-bank-v31.mjs --emit. No editar a mano;
-- cambia docs/prompts/copy-banks/coberturas.exportadores.vertical.v2.md y re-genera.
--
-- Corre DESPUÉS de seed_20260820_copy_bank_v31.sql (que borra e inserta el banco
-- maestro): agrega los verticales sin tocar ese seed.
--
-- Idempotente: el índice único (business, branch, corridor, lower(headline))
-- para status in ('approved','seed') hace que un re-run no duplique.
-- ---------------------------------------------------------------------------

insert into public.copy_bank_items (
  business_id, branch_slug, corridor, industry,
  headline, subcopy, cta, cta_alt,
  angle_tag, angle_label, formula, tone_bucket,
  needs_legal_note, legal_note,
  status, source, prompt_revision, kit_version, business_side
)
select
  b.id,
  v.branch_slug, v.corridor, v.industry,
  v.headline, v.subcopy, v.cta, v.cta_alt,
  v.angle_tag, v.angle_label, v.formula, v.tone_bucket,
  v.needs_legal_note, v.legal_note,
  v.status, v.source, v.prompt_revision, v.kit_version, v.business_side
from (values
  ('coberturas', 'industria', 'autopartes', 'Los arneses ya tienen precio. Tu ingreso en pesos todavía puede cambiar', 'La factura está en dólares y el cobro llegará después.', 'Protege tus ingresos', '{}'::text[], 'precio_pactado_ingreso_mxn_variable', 'precio pactado / ingreso MXN variable', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'autopartes', 'Sensores exportados. Tu cobro en dólares llega en 60 días', 'El tipo de cambio puede modificar el margen que calculaste al vender.', 'Protege tu margen', '{}'::text[], 'exportacion_60_dias', 'exportación + 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'autopartes', 'Las transmisiones se vendieron en dólares. Tus costos quedaron en pesos', 'Una cobertura puede ayudarte a cuidar el resultado hasta recibir el pago.', 'Protege tu margen', '{}'::text[], 'ingreso_usd_costos_mxn', 'ingreso USD / costos MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'autopartes', 'Exportas asientos cada mes. El ingreso en pesos puede cambiar cada mes', 'Las facturas vencen en fechas distintas y el tipo de cambio también puede hacerlo.', 'Da estabilidad a tu margen', '{}'::text[], 'ventas_recurrentes', 'ventas recurrentes', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'autopartes', 'Cotizaste los frenos para ganar el programa. El tipo de cambio puede cambiar la ecuación', 'Una cobertura puede ayudarte a proteger el margen con el que competiste.', 'Protege tu margen', '{}'::text[], 'competitividad', 'competitividad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'autopartes', 'Las baterías tienen precio fijo para todo el proyecto', 'El valor en pesos de los cobros todavía puede cambiar durante el programa.', 'Da certidumbre a tus ingresos', '{}'::text[], 'precio_fijo_proyecto_largo', 'precio fijo / proyecto largo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'autopartes', 'Los sensores ya se vendieron. Ese margen ya está en tu presupuesto', 'El tipo de cambio todavía puede moverlo antes del cobro.', 'Protege tu margen', '{}'::text[], 'margen_comprometido', 'margen comprometido', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'autopartes', 'Tres embarques de suspensión. Tres fechas distintas para cobrar', 'El mismo precio en dólares puede representar distintos ingresos en pesos.', 'Protege tus exportaciones', '{}'::text[], 'varias_facturas_varias_fechas', 'varias facturas / varias fechas', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'autopartes', 'Los módulos ya están facturados. Monto y fecha de cobro ya están definidos', 'Un forward puede ayudarte a definir también el tipo de cambio.', 'Define hoy. Cobra después.', '{}'::text[], 'monto_fecha_conocidos', 'monto + fecha conocidos', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'autopartes', 'Los motores se cobran en 90 días. Hoy ya conoces la factura', 'Un forward puede reducir la incertidumbre cambiaria antes del vencimiento.', 'Cotiza un forward', '{}'::text[], 'factura_a_90_dias', 'factura a 90 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'Los servidores tienen precio en dólares. Tu presupuesto de caja está en pesos', 'Una cobertura puede darte mayor certidumbre sobre el ingreso futuro.', 'Protege tus ingresos', '{}'::text[], 'ingreso_usd_presupuesto_mxn', 'ingreso USD / presupuesto MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'Las computadoras ya se exportaron. Cobrarás dentro de 60 días', 'El tipo de cambio todavía puede modificar el resultado de la venta.', 'Protege tu margen', '{}'::text[], 'exportacion_60_dias', 'exportación + 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'Miles de tarjetas electrónicas hacen relevante una variación pequeña', 'El efecto también se multiplica cuando el lote es grande.', 'Protege el margen de tus exportaciones', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'El precio de los displays ya quedó fijo. El ingreso en pesos no', 'La factura seguirá en dólares hasta la fecha de cobro.', 'Da certidumbre a tus ingresos', '{}'::text[], 'precio_fijo_ingreso_variable', 'precio fijo / ingreso variable', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'Las cámaras ya tienen precio. Tu flujo en pesos todavía puede cambiar', 'Una cobertura puede ayudarte a reducir esa incertidumbre.', 'Protege tus ingresos', '{}'::text[], 'flujo_esperado', 'flujo esperado', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'Dos lotes de fuentes de poder. Dos clientes. Dos vencimientos', 'Cada factura puede convertirse a pesos bajo condiciones distintas.', 'Administra tu riesgo cambiario', '{}'::text[], 'dos_clientes_dos_fechas', 'dos clientes / dos fechas', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'Los sensores ya se vendieron con margen calculado', 'Ese margen todavía puede moverse antes de recibir los dólares.', 'Protege tu margen', '{}'::text[], 'margen_comprometido', 'margen comprometido', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'Los cargadores ya se vendieron. El siguiente lote necesita pesos para producirse', 'Dar mayor certidumbre al ingreso puede estabilizar el siguiente ciclo.', 'Da estabilidad a tu margen', '{}'::text[], 'siguiente_ciclo_productivo', 'siguiente ciclo productivo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'Los servidores se cobran dentro de 90 días', 'Un forward puede ayudarte a definir hoy el tipo de cambio de esa venta.', 'Fija hoy tu tipo de cambio', '{}'::text[], 'cobro_a_90_dias', 'cobro a 90 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'electronicos', 'Las pantallas ya tienen monto, moneda y fecha de cobro', 'Monto y fecha están definidos. El tipo de cambio también puede estarlo.', 'Define hoy. Cobra después.', '{}'::text[], 'monto_fecha_conocidos', 'monto + fecha conocidos', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'Los transformadores se venden en dólares. Fabricarlos cuesta pesos', 'El tipo de cambio puede cambiar el margen mientras esperas el cobro.', 'Protege tu margen', '{}'::text[], 'venta_usd_costos_mxn', 'venta USD / costos MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'El tablero ya está instalado. La factura vence en 60 días', 'Una cobertura puede darte mayor certidumbre sobre ese ingreso.', 'Protege tus ingresos', '{}'::text[], 'instalacion_60_dias', 'instalación + 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'Miles de breakers hacen grande una variación pequeña', 'El tipo de cambio puede modificar el margen de todo el pedido.', 'Protege tu margen', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'El cableado tiene precio fijo durante todo el contrato', 'El equivalente en pesos de cada factura todavía puede cambiar.', 'Da estabilidad a tu margen', '{}'::text[], 'contrato_de_largo_plazo', 'contrato de largo plazo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'Los conectores ya se exportaron. Falta convertir esa venta en pesos', 'Una cobertura puede ayudarte a proteger el resultado hasta cobrar.', 'Protege lo que ya vendiste', '{}'::text[], 'venta_realizada_cobro_pendiente', 'venta realizada / cobro pendiente', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'Tres pedidos de controles eléctricos. Tres fechas distintas de cobro', 'Cada vencimiento puede traer un resultado diferente en pesos.', 'Protege tus exportaciones', '{}'::text[], 'varias_fechas', 'varias fechas', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'Cotizaste las luminarias para ganar el proyecto. El margen quedó comprometido desde entonces', 'El tipo de cambio todavía puede modificarlo antes del cobro.', 'Protege tu margen', '{}'::text[], 'competitividad_margen_comprometido', 'competitividad / margen comprometido', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'Los arneses eléctricos ya están facturados. Ese ingreso ya está en el presupuesto', 'Una cobertura puede dar mayor certidumbre sobre cuánto llegará en pesos.', 'Da certidumbre a tus ingresos', '{}'::text[], 'ingreso_presupuestado', 'ingreso presupuestado', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'El transformador se cobra dentro de 90 días', 'Un forward puede ayudarte a definir hoy el tipo de cambio.', 'Define hoy. Cobra después.', '{}'::text[], 'cobro_a_90_dias', 'cobro a 90 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_electrico', 'Los breakers ya tienen factura, monto y vencimiento', 'Un forward puede ayudarte a definir el componente cambiario antes del cobro.', 'Cotiza un forward', '{}'::text[], 'factura_definida', 'factura definida', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'Los catéteres se venden en dólares. Producirlos cuesta pesos', 'Una cobertura puede ayudarte a proteger el margen de cada pedido.', 'Protege tu margen', '{}'::text[], 'venta_usd_costos_mxn', 'venta USD / costos MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'El instrumental ya se exportó. La factura sigue pendiente', 'El ingreso equivalente en pesos todavía puede cambiar.', 'Protege tus ingresos', '{}'::text[], 'producto_entregado_cobro_pendiente', 'producto entregado / cobro pendiente', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'Miles de sets médicos hacen relevante cualquier movimiento cambiario', 'Una variación puede modificar el resultado del lote completo.', 'Protege el margen de tus exportaciones', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'Los monitores ya tienen precio pactado. El margen todavía puede moverse', 'El cobro llegará después y seguirá denominado en dólares.', 'Protege tu margen', '{}'::text[], 'precio_pactado_margen_variable', 'precio pactado / margen variable', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'Los consumibles médicos salen cada semana. Los cobros llegan después', 'La recurrencia también multiplica las fechas de exposición.', 'Administra tu riesgo cambiario', '{}'::text[], 'ventas_recurrentes', 'ventas recurrentes', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'El equipo de diagnóstico se cobra en 60 días. Ese ingreso ya está presupuestado', 'Una cobertura puede darte mayor certidumbre sobre el monto en pesos.', 'Da certidumbre a tus ingresos', '{}'::text[], 'ingreso_presupuestado_60_dias', 'ingreso presupuestado + 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'Cotizaste los componentes médicos para mantenerte competitivo', 'El tipo de cambio puede apretar el margen con el que ganaste la venta.', 'Protege tu margen', '{}'::text[], 'competitividad', 'competitividad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'El instrumental ya está vendido. La siguiente producción no espera al cliente', 'Dar mayor certidumbre al ingreso puede ayudar a estabilizar el siguiente ciclo.', 'Protege tus ingresos', '{}'::text[], 'siguiente_ciclo_productivo', 'siguiente ciclo productivo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'El equipo médico se cobra dentro de 90 días', 'Un forward puede ayudarte a definir hoy el tipo de cambio.', 'Fija hoy tu tipo de cambio', '{}'::text[], 'cobro_a_90_dias', 'cobro a 90 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'equipo_medico', 'Los catéteres ya tienen monto y fecha de cobro', 'Un forward puede reducir la incertidumbre cambiaria antes del vencimiento.', 'Cotiza un forward', '{}'::text[], 'monto_fecha_conocidos', 'monto + fecha conocidos', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Los refrigeradores se venden en dólares. La planta trabaja en pesos', 'Una cobertura puede ayudarte a cuidar el margen hasta el cobro.', 'Protege tu margen', '{}'::text[], 'venta_usd_operacion_mxn', 'venta USD / operación MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Los congeladores ya se exportaron. El pago llega después', 'El ingreso en pesos todavía puede cambiar antes de recibirlo.', 'Protege tus ingresos', '{}'::text[], 'producto_exportado_pago_futuro', 'producto exportado / pago futuro', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Cientos de refrigeradores hacen relevante una variación pequeña', 'El tipo de cambio puede modificar el resultado del embarque completo.', 'Protege el margen de tus exportaciones', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Los compresores tienen precio fijo durante todo el programa', 'El equivalente en pesos de cada cobro todavía puede variar.', 'Da estabilidad a tu margen', '{}'::text[], 'programa_precio_fijo', 'programa / precio fijo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Los equipos de refrigeración salen todos los meses', 'Cada factura tiene una fecha distinta para convertirse en pesos.', 'Administra tu riesgo cambiario', '{}'::text[], 'ventas_recurrentes', 'ventas recurrentes', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Las vitrinas refrigeradas ya están instaladas. Esa venta ya está hecha', 'El margen todavía puede moverse antes de recibir los dólares.', 'Protege lo que ya vendiste', '{}'::text[], 'venta_realizada_margen_pendiente', 'venta realizada / margen pendiente', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Cotizaste los congeladores para ganar la temporada', 'El tipo de cambio puede cambiar el margen con el que competiste.', 'Protege tu margen', '{}'::text[], 'competitividad_temporada', 'competitividad / temporada', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Dos contenedores de refrigeradores. Dos clientes. Dos fechas para cobrar', 'El mismo precio en dólares puede producir distintos resultados en pesos.', 'Protege tus exportaciones', '{}'::text[], 'multiples_clientes_fechas', 'múltiples clientes / fechas', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Los compresores se cobran dentro de 60 días', 'Un forward puede ayudarte a definir el tipo de cambio desde hoy.', 'Define hoy. Cobra después.', '{}'::text[], 'cobro_a_60_dias', 'cobro a 60 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'refrigeracion_electrodomesticos', 'Los refrigeradores ya están facturados y tienen vencimiento', 'Un forward puede darte mayor certidumbre antes del cobro.', 'Cotiza un forward', '{}'::text[], 'factura_emitida', 'factura emitida', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'Las sillas se venden en dólares. Fabricarlas cuesta pesos', 'El tipo de cambio puede cambiar el margen antes de recibir el pago.', 'Protege tu margen', '{}'::text[], 'venta_usd_costos_mxn', 'venta USD / costos MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'El mobiliario del hotel ya está instalado. Cobrarás en 60 días', 'Una cobertura puede ayudarte a proteger el ingreso de esa venta.', 'Protege tus ingresos', '{}'::text[], 'proyecto_entregado_60_dias', 'proyecto entregado + 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'Cientos de mesas hacen relevante el tipo de cambio del cobro', 'Una variación puede modificar el margen de todo el proyecto.', 'Protege tu margen', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'Los gabinetes ya tienen precio firmado para todo el proyecto', 'El ingreso en pesos todavía puede cambiar entre hoy y el cobro.', 'Da estabilidad a tu margen', '{}'::text[], 'proyecto_precio_fijo', 'proyecto / precio fijo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'Las luminarias salen hacia varios proyectos durante el mes', 'Cada factura también tiene una fecha distinta de vencimiento.', 'Protege tus exportaciones', '{}'::text[], 'multiples_proyectos', 'múltiples proyectos', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'El mobiliario de oficina ya está vendido. El margen todavía puede moverse', 'El tipo de cambio sigue presente mientras la factura continúe en dólares.', 'Protege lo que ya vendiste', '{}'::text[], 'venta_hecha_margen_pendiente', 'venta hecha / margen pendiente', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'Cotizaste las sillas para ganar el proyecto. Ahora hay que proteger ese margen', 'Una cobertura puede ayudarte a reducir la incertidumbre hasta el cobro.', 'Protege tu margen', '{}'::text[], 'competitividad', 'competitividad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'Tres embarques de mesas. Tres fechas para recibir los dólares', 'Cada venta puede terminar representando un monto distinto en pesos.', 'Da certidumbre a tus ingresos', '{}'::text[], 'varios_embarques', 'varios embarques', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'Las luminarias se cobran dentro de 90 días', 'Un forward puede ayudarte a definir hoy el tipo de cambio.', 'Define hoy tu tipo de cambio', '{}'::text[], 'cobro_a_90_dias', 'cobro a 90 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'mobiliario', 'El proyecto de mobiliario ya tiene factura y vencimiento', 'Monto y fecha están definidos. El tipo de cambio también puede estarlo.', 'Define hoy. Cobra después.', '{}'::text[], 'factura_vencimiento', 'factura + vencimiento', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'El aguacate ya se vendió. El margen todavía puede moverse', 'La venta está en dólares y los costos de producción quedaron en pesos.', 'Protege tu margen', '{}'::text[], 'venta_usd_costos_mxn', 'venta USD / costos MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'Las fresas ya cruzaron la frontera. Cobrarás en 30 días', 'El tipo de cambio puede cambiar lo que esa factura represente en pesos.', 'Protege tus ingresos', '{}'::text[], 'embarque_30_dias', 'embarque + 30 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'Vendiste tomate en dólares. Cosecharlo y empacarlo costó pesos', 'Una cobertura puede ayudarte a cuidar el margen hasta el cobro.', 'Protege tu margen', '{}'::text[], 'costos_agricolas_mxn', 'costos agrícolas MXN', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'Las berries salen cada semana. Los dólares llegan en fechas distintas', 'Cada factura puede convertirse a pesos bajo un tipo de cambio diferente.', 'Protege tus exportaciones', '{}'::text[], 'temporada_recurrencia', 'temporada / recurrencia', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'El pimiento ya tiene precio de venta. El ingreso en pesos todavía no', 'Una cobertura puede darte mayor certidumbre hasta recibir el pago.', 'Da certidumbre a tus ingresos', '{}'::text[], 'precio_fijo_ingreso_variable', 'precio fijo / ingreso variable', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'Vendiste limón con margen. La siguiente cosecha ya necesita recursos', 'Proteger el ingreso puede dar mayor estabilidad entre un ciclo y otro.', 'Protege tus ingresos', '{}'::text[], 'siguiente_ciclo_agricola', 'siguiente ciclo agrícola', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'Cotizaste el mango para competir en temporada', 'El tipo de cambio puede modificar el margen con el que ganaste esa venta.', 'Protege tu margen', '{}'::text[], 'competitividad_temporada', 'competitividad / temporada', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'Cosechar, seleccionar y empacar el aguacate ya costó pesos', 'El valor en pesos de la venta todavía puede cambiar hasta el cobro.', 'Protege lo que ya vendiste', '{}'::text[], 'costos_ya_realizados', 'costos ya realizados', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'Las berries se cobran dentro de 30 días', 'Un forward puede ayudarte a definir el tipo de cambio antes del cobro.', 'Cotiza un forward', '{}'::text[], 'cobro_a_30_dias', 'cobro a 30 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'agro_fresco', 'El tomate ya tiene monto y fecha de pago', 'La venta está definida. El tipo de cambio también puede definirse.', 'Define hoy. Cobra después.', '{}'::text[], 'monto_fecha_conocidos', 'monto + fecha conocidos', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'Vendiste café en dólares. Producirlo costó pesos', 'Una cobertura puede ayudarte a cuidar el margen hasta recibir el pago.', 'Protege tu margen', '{}'::text[], 'produccion_mxn_venta_usd', 'producción MXN / venta USD', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'El tequila ya salió hacia el cliente. La factura vence en 60 días', 'El ingreso equivalente en pesos todavía puede cambiar.', 'Protege tus ingresos', '{}'::text[], 'embarque_60_dias', 'embarque + 60 días', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'Miles de cajas de panificación hacen relevante cualquier variación cambiaria', 'El volumen puede amplificar el efecto sobre el margen del pedido.', 'Protege el margen de tus exportaciones', '{}'::text[], 'volumen', 'volumen', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'La confitería ya tiene precio pactado en dólares', 'El resultado en pesos todavía puede cambiar antes del cobro.', 'Da estabilidad a tu margen', '{}'::text[], 'precio_pactado_ingreso_variable', 'precio pactado / ingreso variable', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'La cerveza sale cada mes. Los clientes pagan en fechas distintas', 'Una cobertura puede ayudarte a administrar el riesgo entre varias facturas.', 'Administra tu riesgo cambiario', '{}'::text[], 'ventas_recurrentes', 'ventas recurrentes', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'La fruta procesada ya está vendida. La siguiente producción viene después', 'Dar mayor certidumbre al ingreso puede ayudar a estabilizar el siguiente ciclo.', 'Protege tus ingresos', '{}'::text[], 'siguiente_ciclo_productivo', 'siguiente ciclo productivo', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'Cotizaste la salsa para ganar espacio con el distribuidor', 'El tipo de cambio puede modificar el margen con el que competiste.', 'Protege tu margen', '{}'::text[], 'competitividad', 'competitividad', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'Tres embarques de café. Tres fechas distintas para cobrar', 'El mismo precio en dólares puede representar distintos montos en pesos.', 'Protege tus exportaciones', '{}'::text[], 'varios_embarques', 'varios embarques', null::text, null::text, false, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'El tequila se cobra dentro de 60 días', 'Un forward puede ayudarte a definir hoy el tipo de cambio.', 'Fija hoy tu tipo de cambio', '{}'::text[], 'cobro_a_60_dias', 'cobro a 60 días', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador'),
  ('coberturas', 'industria', 'alimentos_bebidas', 'El café ya tiene monto, moneda y vencimiento', 'Un forward puede darte mayor certidumbre antes de la fecha de cobro.', 'Cotiza un forward', '{}'::text[], 'monto_fecha_conocidos', 'monto + fecha conocidos', null::text, null::text, true, null::text, 'seed', 'seed', 'seed-v3.1', 'coberturas-forwards-v3.1', 'exportador')
) as v(
  branch_slug, corridor, industry,
  headline, subcopy, cta, cta_alt,
  angle_tag, angle_label, formula, tone_bucket,
  needs_legal_note, legal_note,
  status, source, prompt_revision, kit_version, business_side
)
cross join (select id from public.business_tenants where slug = 'xending') b
on conflict do nothing;

-- Verificación
select branch_slug, corridor, count(*) as n
from public.copy_bank_items
where status = 'seed'
group by 1, 2
order by 1, 2;
