// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdfhytvjnzdovjfovqfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkZmh5dHZqbnpkb3ZqZm92cWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDkxNDgsImV4cCI6MjA2OTU4NTE0OH0.c_6XBEJQ4aTQr4AvaHznrerfUBedZ_0c-7qjggKBlwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});